CREATE SCHEMA IF NOT EXISTS news;

CREATE TABLE news.region_month_signal_import_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind varchar(32) NOT NULL,
    method_version varchar(64) NOT NULL,
    dataset_tier varchar(32) NOT NULL,
    input_path text,
    row_count integer NOT NULL DEFAULT 0,
    snapshot_upsert_count integer NOT NULL DEFAULT 0,
    evidence_upsert_count integer NOT NULL DEFAULT 0,
    status varchar(16) NOT NULL,
    failure_reason text,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT region_month_signal_import_run_source_kind_allowed CHECK (source_kind IN ('BIGKINDS_CSV', 'AGENT_WEB_RESEARCH')),
    CONSTRAINT region_month_signal_import_run_dataset_tier_allowed CHECK (dataset_tier IN ('EXPERIMENTAL_SEED', 'OBSERVED_SIGNAL')),
    CONSTRAINT region_month_signal_import_run_status_allowed CHECK (status IN ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED')),
    CONSTRAINT region_month_signal_import_run_counts_non_negative CHECK (
        row_count >= 0
        AND snapshot_upsert_count >= 0
        AND evidence_upsert_count >= 0
    )
);

CREATE TABLE news.region_month_signal_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_bucket varchar(64) NOT NULL,
    signal_month date NOT NULL,
    source_kind varchar(32) NOT NULL,
    method_version varchar(64) NOT NULL,
    dataset_tier varchar(32) NOT NULL,
    news_count integer NOT NULL DEFAULT 0,
    matched_news_count integer NOT NULL DEFAULT 0,
    direct_evidence_count integer NOT NULL DEFAULT 0,
    inherited_evidence_count integer NOT NULL DEFAULT 0,
    policy_positive_score integer NOT NULL DEFAULT 0,
    policy_negative_score integer NOT NULL DEFAULT 0,
    redevelopment_score integer NOT NULL DEFAULT 0,
    transport_score integer NOT NULL DEFAULT 0,
    supply_risk_score integer NOT NULL DEFAULT 0,
    sale_market_score integer NOT NULL DEFAULT 0,
    rental_market_score integer NOT NULL DEFAULT 0,
    price_up_signal integer NOT NULL DEFAULT 0,
    price_down_signal integer NOT NULL DEFAULT 0,
    confidence numeric(4,3) NOT NULL,
    aggregate_note text NOT NULL,
    import_run_id bigint REFERENCES news.region_month_signal_import_run (id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT region_month_signal_snapshot_unique UNIQUE (region_bucket, signal_month, method_version),
    CONSTRAINT region_month_signal_snapshot_source_kind_allowed CHECK (source_kind IN ('BIGKINDS_CSV', 'AGENT_WEB_RESEARCH')),
    CONSTRAINT region_month_signal_snapshot_dataset_tier_allowed CHECK (dataset_tier IN ('EXPERIMENTAL_SEED', 'OBSERVED_SIGNAL')),
    CONSTRAINT region_month_signal_snapshot_month_first_day CHECK (date_trunc('month', signal_month)::date = signal_month),
    CONSTRAINT region_month_signal_snapshot_counts_non_negative CHECK (
        news_count >= 0
        AND matched_news_count >= 0
        AND direct_evidence_count >= 0
        AND inherited_evidence_count >= 0
    ),
    CONSTRAINT region_month_signal_snapshot_scores_range CHECK (
        policy_positive_score BETWEEN 0 AND 100
        AND policy_negative_score BETWEEN 0 AND 100
        AND redevelopment_score BETWEEN 0 AND 100
        AND transport_score BETWEEN 0 AND 100
        AND supply_risk_score BETWEEN 0 AND 100
        AND sale_market_score BETWEEN 0 AND 100
        AND rental_market_score BETWEEN 0 AND 100
        AND price_up_signal BETWEEN 0 AND 100
        AND price_down_signal BETWEEN 0 AND 100
    ),
    CONSTRAINT region_month_signal_snapshot_confidence_range CHECK (confidence BETWEEN 0 AND 1),
    CONSTRAINT region_month_signal_snapshot_no_forbidden_note CHECK (
        aggregate_note !~* '(본문|내용|원문|기사본문|content|body|full_text|html|article_html|summary|article_summary)'
    )
);

CREATE INDEX region_month_signal_snapshot_month_idx
    ON news.region_month_signal_snapshot (signal_month, region_bucket);

CREATE TABLE news.region_month_signal_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id bigint NOT NULL REFERENCES news.region_month_signal_snapshot (id) ON DELETE CASCADE,
    source_key varchar(160) NOT NULL,
    title text NOT NULL,
    publisher varchar(255) NOT NULL,
    published_date date,
    url text,
    citation_url text,
    topic_tags jsonb NOT NULL DEFAULT '[]'::jsonb,
    evidence_scope varchar(16) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT region_month_signal_evidence_unique UNIQUE (snapshot_id, source_key),
    CONSTRAINT region_month_signal_evidence_scope_allowed CHECK (evidence_scope IN ('DIRECT', 'INHERITED')),
    CONSTRAINT region_month_signal_evidence_topic_tags_array CHECK (jsonb_typeof(topic_tags) = 'array'),
    CONSTRAINT region_month_signal_evidence_no_forbidden_text CHECK (
        title !~* '(본문|내용|원문|기사본문|content|body|full_text|html|article_html|summary|article_summary)'
        AND publisher !~* '(본문|내용|원문|기사본문|content|body|full_text|html|article_html|summary|article_summary)'
    )
);

CREATE INDEX region_month_signal_evidence_snapshot_idx
    ON news.region_month_signal_evidence (snapshot_id);
