CREATE SCHEMA IF NOT EXISTS news;

CREATE TABLE news.source_policy (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source varchar(32) NOT NULL UNIQUE,
    policy_version varchar(32) NOT NULL,
    metadata_collection_allowed boolean NOT NULL DEFAULT true,
    publisher_page_fetch_allowed boolean NOT NULL DEFAULT false,
    full_text_storage_allowed boolean NOT NULL DEFAULT false,
    snippet_storage_allowed boolean NOT NULL DEFAULT true,
    raw_payload_retention_days integer NOT NULL DEFAULT 30,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT source_policy_source_allowed CHECK (source IN ('NAVER_NEWS_SEARCH')),
    CONSTRAINT source_policy_raw_payload_retention_days_range CHECK (raw_payload_retention_days BETWEEN 0 AND 3650)
);

INSERT INTO news.source_policy (
    source,
    policy_version,
    metadata_collection_allowed,
    publisher_page_fetch_allowed,
    full_text_storage_allowed,
    snippet_storage_allowed,
    raw_payload_retention_days,
    notes
)
VALUES (
    'NAVER_NEWS_SEARCH',
    'naver-news-search-metadata-v1',
    true,
    false,
    false,
    true,
    30,
    'Metadata and official snippets only. Publisher pages and full text are outside Slice 01.'
);

CREATE TABLE news.signal_extraction_profile (
    extraction_version varchar(64) PRIMARY KEY,
    provider varchar(32) NOT NULL DEFAULT 'OPENAI',
    model varchar(128) NOT NULL,
    prompt_version varchar(64) NOT NULL,
    schema_version varchar(64) NOT NULL,
    prompt_hash char(64) NOT NULL,
    json_schema_hash char(64) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    retired_at timestamptz,
    CONSTRAINT signal_extraction_profile_provider_allowed CHECK (provider IN ('OPENAI')),
    CONSTRAINT signal_extraction_profile_prompt_hash_sha256 CHECK (prompt_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT signal_extraction_profile_json_schema_hash_sha256 CHECK (json_schema_hash ~ '^[0-9a-f]{64}$')
);

CREATE UNIQUE INDEX signal_extraction_profile_one_active_per_provider_idx
    ON news.signal_extraction_profile (provider)
    WHERE active;

CREATE TABLE news.collection_keyword (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_text varchar(255) NOT NULL,
    normalized_query_text varchar(255) NOT NULL,
    keyword_type varchar(16) NOT NULL,
    source_table varchar(64),
    source_id bigint,
    priority integer NOT NULL DEFAULT 100,
    cadence varchar(16) NOT NULL DEFAULT 'MANUAL',
    enabled boolean NOT NULL DEFAULT true,
    next_due_at timestamptz,
    last_collected_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT collection_keyword_type_allowed CHECK (keyword_type IN ('TOPIC', 'REGION', 'COMPLEX', 'ALIAS')),
    CONSTRAINT collection_keyword_cadence_allowed CHECK (cadence IN ('MANUAL', 'DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT collection_keyword_priority_range CHECK (priority BETWEEN 0 AND 1000),
    CONSTRAINT collection_keyword_source_pair CHECK ((source_table IS NULL AND source_id IS NULL) OR (source_table IS NOT NULL AND source_id IS NOT NULL))
);

CREATE UNIQUE INDEX collection_keyword_identity_idx
    ON news.collection_keyword (normalized_query_text, keyword_type, COALESCE(source_table, ''), COALESCE(source_id, 0));

CREATE INDEX collection_keyword_due_idx
    ON news.collection_keyword (enabled, next_due_at, priority DESC);

CREATE TABLE news.collection_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_mode varchar(16) NOT NULL,
    status varchar(16) NOT NULL,
    trigger_query_text varchar(255),
    max_keywords integer NOT NULL,
    display_limit integer NOT NULL,
    max_articles integer NOT NULL,
    keyword_count integer NOT NULL DEFAULT 0,
    provider_item_count integer NOT NULL DEFAULT 0,
    observed_new_count integer NOT NULL DEFAULT 0,
    observed_duplicate_count integer NOT NULL DEFAULT 0,
    feature_created_count integer NOT NULL DEFAULT 0,
    feature_skipped_count integer NOT NULL DEFAULT 0,
    failed_count integer NOT NULL DEFAULT 0,
    obsidian_export_path text,
    notification_status varchar(16) NOT NULL DEFAULT 'NOT_REQUESTED',
    failure_reason text,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT collection_run_mode_allowed CHECK (run_mode IN ('RUN_ONCE', 'DAILY')),
    CONSTRAINT collection_run_status_allowed CHECK (status IN ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED')),
    CONSTRAINT collection_run_notification_status_allowed CHECK (notification_status IN ('NOT_REQUESTED', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT collection_run_non_negative_counts CHECK (
        max_keywords >= 0
        AND display_limit >= 0
        AND max_articles >= 0
        AND keyword_count >= 0
        AND provider_item_count >= 0
        AND observed_new_count >= 0
        AND observed_duplicate_count >= 0
        AND feature_created_count >= 0
        AND feature_skipped_count >= 0
        AND failed_count >= 0
    )
);

CREATE INDEX collection_run_started_at_idx ON news.collection_run (started_at DESC);
CREATE INDEX collection_run_status_started_at_idx ON news.collection_run (status, started_at DESC);

CREATE TABLE news.collection_run_keyword (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL REFERENCES news.collection_run (id) ON DELETE CASCADE,
    keyword_id bigint REFERENCES news.collection_keyword (id) ON DELETE SET NULL,
    query_text varchar(255) NOT NULL,
    normalized_query_text varchar(255) NOT NULL,
    keyword_type varchar(16) NOT NULL,
    provider varchar(32) NOT NULL DEFAULT 'NAVER_NEWS_SEARCH',
    display_limit integer NOT NULL,
    sort_order varchar(16) NOT NULL DEFAULT 'date',
    status varchar(16) NOT NULL,
    provider_total integer,
    provider_start integer,
    provider_display integer,
    fetched_count integer NOT NULL DEFAULT 0,
    observed_new_count integer NOT NULL DEFAULT 0,
    observed_duplicate_count integer NOT NULL DEFAULT 0,
    feature_created_count integer NOT NULL DEFAULT 0,
    failed_count integer NOT NULL DEFAULT 0,
    failure_reason text,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    CONSTRAINT collection_run_keyword_provider_allowed CHECK (provider IN ('NAVER_NEWS_SEARCH')),
    CONSTRAINT collection_run_keyword_sort_order_allowed CHECK (sort_order IN ('date', 'sim')),
    CONSTRAINT collection_run_keyword_status_allowed CHECK (status IN ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED')),
    CONSTRAINT collection_run_keyword_type_allowed CHECK (keyword_type IN ('TOPIC', 'REGION', 'COMPLEX', 'ALIAS')),
    CONSTRAINT collection_run_keyword_counts_valid CHECK (
        display_limit >= 0
        AND (provider_total IS NULL OR provider_total >= 0)
        AND (provider_start IS NULL OR provider_start > 0)
        AND (provider_display IS NULL OR provider_display >= 0)
        AND fetched_count >= 0
        AND observed_new_count >= 0
        AND observed_duplicate_count >= 0
        AND feature_created_count >= 0
        AND failed_count >= 0
    )
);

CREATE UNIQUE INDEX collection_run_keyword_identity_idx
    ON news.collection_run_keyword (run_id, normalized_query_text, keyword_type);

CREATE INDEX collection_run_keyword_keyword_started_at_idx
    ON news.collection_run_keyword (keyword_id, started_at DESC);

CREATE TABLE news.article_observation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source varchar(32) NOT NULL,
    source_key varchar(128) NOT NULL,
    publisher varchar(255) NOT NULL,
    title text NOT NULL,
    url text,
    provider_url text NOT NULL,
    snippet text,
    published_at timestamptz,
    provider_pub_at timestamptz,
    first_seen_at timestamptz NOT NULL,
    collected_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    news_date_kst date NOT NULL,
    raw_provider_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    payload_hash char(64) NOT NULL,
    ingest_status varchar(24) NOT NULL,
    failure_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT article_observation_source_key_unique UNIQUE (source, source_key),
    CONSTRAINT article_observation_source_allowed CHECK (source IN ('NAVER_NEWS_SEARCH')),
    CONSTRAINT article_observation_ingest_status_allowed CHECK (ingest_status IN ('OBSERVED', 'FEATURED', 'SKIPPED_IRRELEVANT', 'FETCH_FAILED', 'PARSE_FAILED', 'TERMS_BLOCKED')),
    CONSTRAINT article_observation_payload_hash_sha256 CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT article_observation_raw_provider_payload_object CHECK (jsonb_typeof(raw_provider_payload) = 'object'),
    CONSTRAINT article_observation_raw_provider_payload_no_body CHECK (
        NOT (raw_provider_payload ?| ARRAY['content', 'body', 'full_text', 'html', 'article_html', 'summary'])
    )
);

CREATE INDEX article_observation_first_seen_at_idx ON news.article_observation (first_seen_at);
CREATE INDEX article_observation_news_date_kst_idx ON news.article_observation (news_date_kst);
CREATE INDEX article_observation_provider_pub_at_idx ON news.article_observation (provider_pub_at);
CREATE INDEX article_observation_source_provider_pub_at_idx ON news.article_observation (source, provider_pub_at DESC);

CREATE TABLE news.collection_run_article (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_keyword_id bigint NOT NULL REFERENCES news.collection_run_keyword (id) ON DELETE CASCADE,
    article_observation_id bigint REFERENCES news.article_observation (id) ON DELETE SET NULL,
    source varchar(32),
    source_key varchar(128),
    provider_rank integer,
    title_snapshot text,
    provider_url_snapshot text,
    discovery_status varchar(32) NOT NULL,
    failure_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT collection_run_article_discovery_status_allowed CHECK (discovery_status IN ('NEW_OBSERVATION', 'DUPLICATE_OBSERVATION', 'FEATURE_CREATED', 'FEATURE_SKIPPED', 'FAILED')),
    CONSTRAINT collection_run_article_provider_rank_positive CHECK (provider_rank IS NULL OR provider_rank > 0)
);

CREATE UNIQUE INDEX collection_run_article_run_keyword_source_key_idx
    ON news.collection_run_article (run_keyword_id, source, source_key)
    WHERE source_key IS NOT NULL;

CREATE INDEX collection_run_article_observation_idx ON news.collection_run_article (article_observation_id);
CREATE INDEX collection_run_article_run_keyword_idx ON news.collection_run_article (run_keyword_id);

CREATE TABLE news.signal_feature (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_observation_id bigint NOT NULL REFERENCES news.article_observation (id) ON DELETE RESTRICT,
    source varchar(32) NOT NULL,
    source_key varchar(128) NOT NULL,
    feature_date_kst date NOT NULL,
    first_seen_at timestamptz NOT NULL,
    region_tags jsonb NOT NULL DEFAULT '[]'::jsonb,
    complex_candidates jsonb NOT NULL DEFAULT '[]'::jsonb,
    topic_tags jsonb NOT NULL DEFAULT '[]'::jsonb,
    impact_target varchar(32) NOT NULL,
    impact_direction varchar(16) NOT NULL,
    sentiment varchar(16) NOT NULL,
    confidence numeric(4,3) NOT NULL,
    extraction_version varchar(64) NOT NULL REFERENCES news.signal_extraction_profile (extraction_version),
    evidence_level varchar(32) NOT NULL,
    model varchar(128) NOT NULL,
    prompt_version varchar(64) NOT NULL,
    input_hash char(64) NOT NULL,
    structured_output jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT signal_feature_source_key_version_unique UNIQUE (source, source_key, extraction_version),
    CONSTRAINT signal_feature_observation_version_unique UNIQUE (article_observation_id, extraction_version),
    CONSTRAINT signal_feature_impact_target_allowed CHECK (impact_target IN ('sale_price', 'jeonse_price', 'volume', 'supply', 'liquidity', 'risk')),
    CONSTRAINT signal_feature_impact_direction_allowed CHECK (impact_direction IN ('up', 'down', 'mixed', 'unknown')),
    CONSTRAINT signal_feature_sentiment_allowed CHECK (sentiment IN ('positive', 'neutral', 'negative', 'mixed')),
    CONSTRAINT signal_feature_evidence_level_allowed CHECK (evidence_level IN ('title', 'snippet', 'licensed_full_text', 'public_press_release')),
    CONSTRAINT signal_feature_confidence_range CHECK (confidence BETWEEN 0 AND 1),
    CONSTRAINT signal_feature_region_tags_array CHECK (jsonb_typeof(region_tags) = 'array'),
    CONSTRAINT signal_feature_complex_candidates_array CHECK (jsonb_typeof(complex_candidates) = 'array'),
    CONSTRAINT signal_feature_topic_tags_array CHECK (jsonb_typeof(topic_tags) = 'array'),
    CONSTRAINT signal_feature_input_hash_sha256 CHECK (input_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT signal_feature_structured_output_object CHECK (jsonb_typeof(structured_output) = 'object'),
    CONSTRAINT signal_feature_structured_output_no_body CHECK (
        NOT (structured_output ?| ARRAY['summary', 'article_summary', 'content', 'body', 'full_text', 'html'])
    )
);

CREATE INDEX signal_feature_first_seen_at_idx ON news.signal_feature (first_seen_at);
CREATE INDEX signal_feature_feature_date_kst_idx ON news.signal_feature (feature_date_kst);
CREATE INDEX signal_feature_impact_idx ON news.signal_feature (impact_target, impact_direction);
CREATE INDEX signal_feature_region_tags_gin_idx ON news.signal_feature USING gin (region_tags);
CREATE INDEX signal_feature_topic_tags_gin_idx ON news.signal_feature USING gin (topic_tags);
CREATE INDEX signal_feature_complex_candidates_gin_idx ON news.signal_feature USING gin (complex_candidates);

CREATE VIEW news.signal_dataset_view AS
SELECT
    observation.source,
    observation.source_key,
    observation.publisher,
    observation.title,
    observation.url,
    observation.published_at,
    observation.provider_pub_at,
    observation.first_seen_at,
    feature.feature_date_kst,
    observation.news_date_kst,
    feature.region_tags,
    feature.complex_candidates,
    feature.topic_tags,
    feature.impact_target,
    feature.impact_direction,
    feature.sentiment,
    feature.confidence,
    feature.extraction_version,
    feature.evidence_level
FROM news.signal_feature feature
JOIN news.article_observation observation
    ON observation.id = feature.article_observation_id;

CREATE VIEW news.article_observation_cleanup_candidate_view AS
SELECT
    observation.id AS article_observation_id,
    observation.source,
    observation.source_key,
    observation.ingest_status,
    observation.first_seen_at,
    observation.collected_at,
    observation.payload_hash,
    'PURGE_RAW_PROVIDER_PAYLOAD'::text AS recommended_action
FROM news.article_observation observation
JOIN news.source_policy policy
    ON policy.source = observation.source
WHERE observation.ingest_status IN ('FEATURED', 'SKIPPED_IRRELEVANT', 'TERMS_BLOCKED')
  AND observation.raw_provider_payload <> '{}'::jsonb
  AND observation.collected_at < now() - make_interval(days => policy.raw_payload_retention_days);
