CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;
CREATE SCHEMA IF NOT EXISTS geo_enrichment;

CREATE TABLE geo_enrichment.vworld_wfs_footprint_cache (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pnu character varying(19) NOT NULL,
    provider character varying(32) NOT NULL DEFAULT 'VWORLD_WFS',
    provider_feature_id character varying(128) NOT NULL,
    building_name character varying(255),
    dong_name character varying(255),
    main_purps_cd character varying(32),
    centroid_lat numeric(10,7) NOT NULL,
    centroid_lng numeric(10,7) NOT NULL,
    geom public.geometry(MultiPolygon,4326) NOT NULL,
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    snapshot_version character varying(64) NOT NULL,
    fetched_at timestamp with time zone NOT NULL DEFAULT now(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT vworld_wfs_footprint_cache_pnu_check CHECK ((pnu)::text ~ '^[0-9]{19}$'::text),
    CONSTRAINT vworld_wfs_footprint_cache_latitude_check CHECK (centroid_lat BETWEEN 33 AND 39),
    CONSTRAINT vworld_wfs_footprint_cache_longitude_check CHECK (centroid_lng BETWEEN 124 AND 132),
    CONSTRAINT vworld_wfs_footprint_cache_geom_srid_check CHECK (public.ST_SRID(geom) = 4326),
    CONSTRAINT vworld_wfs_footprint_cache_geom_valid_check CHECK (public.ST_IsValid(geom)),
    CONSTRAINT uq_vworld_wfs_footprint_cache_source_key
        UNIQUE (provider, provider_feature_id, snapshot_version)
);

CREATE INDEX ix_vworld_wfs_footprint_cache_pnu
    ON geo_enrichment.vworld_wfs_footprint_cache USING btree (pnu);
CREATE INDEX ix_vworld_wfs_footprint_cache_geom
    ON geo_enrichment.vworld_wfs_footprint_cache USING gist (geom);
