CREATE TABLE public.building_register_collection_campaign (
    collection_id uuid PRIMARY KEY,
    mode character varying(16) NOT NULL,
    strategy character varying(24) NOT NULL,
    from_complex_id bigint,
    to_complex_id bigint NOT NULL,
    status character varying(24) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT ck_brc_campaign_mode CHECK (mode IN ('missing', 'retry')),
    CONSTRAINT ck_brc_campaign_strategy CHECK (strategy IN ('ADAPTIVE', 'FULL_HIERARCHY')),
    CONSTRAINT ck_brc_campaign_status CHECK (status IN ('CREATED', 'COLLECTING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_brc_campaign_range CHECK (
        to_complex_id > 0
        AND (from_complex_id IS NULL OR (from_complex_id > 0 AND from_complex_id <= to_complex_id))
    ),
    CONSTRAINT ck_brc_campaign_completion CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL)
        OR (status <> 'COMPLETED' AND completed_at IS NULL)
    )
);

CREATE TABLE public.building_register_collection_target (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id uuid NOT NULL REFERENCES public.building_register_collection_campaign(collection_id),
    target_ordinal bigint NOT NULL,
    complex_id bigint NOT NULL REFERENCES public.complex(id),
    pnu character varying(19) NOT NULL,
    initial_bc_rat numeric(6,2),
    initial_vl_rat numeric(6,2),
    initial_bld_mgm_bld_rgst_pk character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT uq_brc_target_collection_complex UNIQUE (collection_id, complex_id),
    CONSTRAINT uq_brc_target_collection_ordinal UNIQUE (collection_id, target_ordinal),
    CONSTRAINT ck_brc_target_ordinal CHECK (target_ordinal > 0),
    CONSTRAINT ck_brc_target_pnu CHECK (pnu ~ '^[0-9]{19}$'),
    CONSTRAINT ck_brc_target_initial_key CHECK (
        initial_bld_mgm_bld_rgst_pk IS NULL OR btrim(initial_bld_mgm_bld_rgst_pk) <> ''
    )
);

CREATE TABLE public.building_register_endpoint_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id uuid NOT NULL REFERENCES public.building_register_collection_campaign(collection_id),
    pnu character varying(19) NOT NULL,
    endpoint character varying(24) NOT NULL,
    run_date date NOT NULL,
    page_size integer NOT NULL,
    attempt_no integer NOT NULL,
    status character varying(32) NOT NULL,
    total_count integer,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT uq_bre_snapshot_attempt UNIQUE (collection_id, pnu, endpoint, run_date, attempt_no),
    CONSTRAINT ck_bre_snapshot_pnu CHECK (pnu ~ '^[0-9]{19}$'),
    CONSTRAINT ck_bre_snapshot_endpoint CHECK (endpoint IN ('RECAP_TITLE', 'TITLE', 'BASIC_OVERVIEW')),
    CONSTRAINT ck_bre_snapshot_page_size CHECK (page_size IN (10, 25, 50, 100)),
    CONSTRAINT ck_bre_snapshot_attempt CHECK (attempt_no > 0),
    CONSTRAINT ck_bre_snapshot_total CHECK (total_count IS NULL OR total_count >= 0),
    CONSTRAINT ck_bre_snapshot_status CHECK (status IN (
        'ACTIVE', 'PARSED', 'EMPTY', 'ABANDONED_OVERSIZED', 'PERMANENT_OVERSIZED',
        'PROVIDER_FAILED', 'PARSE_FAILED'
    ))
);

CREATE TABLE public.building_register_raw_page (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_snapshot_id bigint NOT NULL REFERENCES public.building_register_endpoint_snapshot(id),
    request_id uuid NOT NULL,
    page_no integer NOT NULL,
    attempt_no integer NOT NULL,
    status character varying(24) NOT NULL,
    response_body text,
    body_sha256 character varying(64) NOT NULL,
    byte_count integer NOT NULL,
    http_status integer,
    provider_status character varying(32),
    failure_reason text,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    finalized_at timestamp with time zone,
    CONSTRAINT uq_brr_page_attempt UNIQUE (endpoint_snapshot_id, page_no, attempt_no),
    CONSTRAINT ck_brr_page_number CHECK (page_no > 0 AND attempt_no > 0),
    CONSTRAINT ck_brr_page_status CHECK (status IN (
        'RECEIVED', 'PARSED', 'EMPTY', 'PROVIDER_FAILED', 'PARSE_FAILED', 'OVERSIZED'
    )),
    CONSTRAINT ck_brr_page_hash CHECK (body_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_brr_page_bytes CHECK (byte_count >= 0),
    CONSTRAINT ck_brr_page_body_limit CHECK (
        response_body IS NULL OR octet_length(response_body) <= 2097152
    ),
    CONSTRAINT ck_brr_page_http_status CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599)
);

CREATE UNIQUE INDEX uq_brr_completed_page
    ON public.building_register_raw_page (endpoint_snapshot_id, page_no)
    WHERE status IN ('PARSED', 'EMPTY');

CREATE TABLE public.building_register_record_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_page_id bigint NOT NULL REFERENCES public.building_register_raw_page(id),
    item_index integer NOT NULL,
    pnu character varying(19) NOT NULL,
    endpoint character varying(24) NOT NULL,
    mgm_bldrgst_pk character varying(255) NOT NULL,
    mgm_up_bldrgst_pk character varying(255),
    regstr_gb_cd character varying(8),
    regstr_kind_cd character varying(8),
    new_old_regstr_gb_cd character varying(8),
    main_atch_gb_cd character varying(8),
    bld_nm character varying(500),
    dong_nm character varying(500),
    main_purps_cd character varying(32),
    plat_area numeric(20,6),
    arch_area numeric(20,6),
    tot_area numeric(20,6),
    vl_rat_estm_tot_area numeric(20,6),
    bc_rat numeric(18,8),
    vl_rat numeric(18,8),
    main_bld_cnt integer,
    atch_bld_cnt integer,
    hhld_cnt integer,
    use_apr_day date,
    crtn_day date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT uq_brs_raw_item UNIQUE (raw_page_id, item_index),
    CONSTRAINT ck_brs_item_index CHECK (item_index >= 0),
    CONSTRAINT ck_brs_pnu CHECK (pnu ~ '^[0-9]{19}$'),
    CONSTRAINT ck_brs_endpoint CHECK (endpoint IN ('RECAP_TITLE', 'TITLE', 'BASIC_OVERVIEW')),
    CONSTRAINT ck_brs_management_key CHECK (btrim(mgm_bldrgst_pk) <> ''),
    CONSTRAINT ck_brs_parent_key CHECK (mgm_up_bldrgst_pk IS NULL OR btrim(mgm_up_bldrgst_pk) <> '')
);

CREATE TABLE public.building_register_complex_match (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id uuid NOT NULL REFERENCES public.building_register_collection_campaign(collection_id),
    complex_id bigint NOT NULL REFERENCES public.complex(id),
    pnu character varying(19) NOT NULL,
    root_management_key character varying(255),
    scope character varying(24) NOT NULL,
    status character varying(32) NOT NULL,
    match_path character varying(32),
    projectable boolean DEFAULT false NOT NULL,
    failure_reason text,
    evaluated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT uq_brcm_collection_complex UNIQUE (collection_id, complex_id),
    CONSTRAINT ck_brcm_pnu CHECK (pnu ~ '^[0-9]{19}$'),
    CONSTRAINT ck_brcm_root_key CHECK (root_management_key IS NULL OR btrim(root_management_key) <> ''),
    CONSTRAINT ck_brcm_scope CHECK (scope IN ('UNIQUE_ROOT', 'STANDALONE_TITLE', 'SHARED_RECAP')),
    CONSTRAINT ck_brcm_status CHECK (status IN (
        'RESOLVED', 'AMBIGUOUS', 'INCOMPLETE_HIERARCHY', 'SOURCE_CONFLICT',
        'AMBIGUOUS_GENERATION', 'SOURCE_MISSING'
    )),
    CONSTRAINT ck_brcm_match_path CHECK (match_path IS NULL OR match_path IN (
        'EXISTING_KEY', 'UNIQUE_PNU', 'EXACT_NAME', 'EXACT_DONG_SET', 'FOOTPRINT_EVIDENCE'
    )),
    CONSTRAINT ck_brcm_projectable CHECK (
        NOT projectable OR (status = 'RESOLVED' AND scope <> 'SHARED_RECAP')
    )
);

CREATE TABLE public.building_register_match_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id bigint NOT NULL REFERENCES public.building_register_complex_match(id),
    evidence_type character varying(32) NOT NULL,
    outcome character varying(16) NOT NULL,
    evidence_value jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_brme_type CHECK (evidence_type IN (
        'EXISTING_KEY', 'PNU_CARDINALITY', 'EXACT_NAME', 'DONG_SET', 'FOOTPRINT_LINK',
        'DONG_COUNT', 'UNIT_COUNT', 'USE_DATE', 'HIERARCHY'
    )),
    CONSTRAINT ck_brme_outcome CHECK (outcome IN ('MATCH', 'MISMATCH', 'INCONCLUSIVE'))
);

CREATE TABLE public.building_ratio_candidate (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id bigint NOT NULL REFERENCES public.building_register_complex_match(id),
    field character varying(32) NOT NULL,
    method character varying(48) NOT NULL,
    value numeric(18,8) NOT NULL,
    projected_value numeric(6,2) NOT NULL,
    numerator numeric(20,6),
    denominator numeric(20,6),
    status character varying(24) NOT NULL,
    selected boolean DEFAULT false NOT NULL,
    reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_brc_field CHECK (field IN ('BUILDING_COVERAGE_RATIO', 'FLOOR_AREA_RATIO')),
    CONSTRAINT ck_brc_method CHECK (method IN (
        'RECAP_DIRECT', 'RECAP_COMPONENT_CALC', 'TITLE_DIRECT_CONSENSUS',
        'RECAP_NUMERATOR_TITLE_DENOMINATOR', 'TITLE_AGGREGATE_CALC',
        'STANDALONE_TITLE_DIRECT', 'STANDALONE_TITLE_COMPONENT_CALC'
    )),
    CONSTRAINT ck_brc_value CHECK (value > 0 AND projected_value > 0 AND projected_value <= 9999.99),
    CONSTRAINT ck_brc_components CHECK (
        (numerator IS NULL OR numerator >= 0) AND (denominator IS NULL OR denominator > 0)
    ),
    CONSTRAINT ck_brc_status CHECK (status IN ('VALID', 'INCOMPLETE', 'SOURCE_CONFLICT')),
    CONSTRAINT uq_brc_identity_scope UNIQUE (id, match_id, field)
);

CREATE UNIQUE INDEX uq_brc_selected_field
    ON public.building_ratio_candidate (match_id, field)
    WHERE selected;

CREATE TABLE public.building_ratio_candidate_input (
    candidate_id bigint NOT NULL REFERENCES public.building_ratio_candidate(id),
    record_snapshot_id bigint NOT NULL REFERENCES public.building_register_record_snapshot(id),
    input_role character varying(24) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (candidate_id, record_snapshot_id, input_role),
    CONSTRAINT ck_brci_role CHECK (input_role IN ('DIRECT', 'NUMERATOR', 'DENOMINATOR', 'HIERARCHY'))
);

CREATE TABLE public.building_ratio_projection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id uuid NOT NULL,
    match_id bigint NOT NULL REFERENCES public.building_register_complex_match(id),
    candidate_id bigint,
    complex_id bigint NOT NULL REFERENCES public.complex(id),
    field character varying(32) NOT NULL,
    outcome character varying(40) NOT NULL,
    previous_value numeric(6,2),
    source_value numeric(6,2),
    applied_value numeric(6,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT uq_brp_request_candidate_field UNIQUE (request_id, candidate_id, field),
    CONSTRAINT uq_brp_request_match_field UNIQUE (request_id, match_id, field),
    CONSTRAINT fk_brp_candidate_scope FOREIGN KEY (candidate_id, match_id, field)
        REFERENCES public.building_ratio_candidate(id, match_id, field),
    CONSTRAINT ck_brp_field CHECK (field IN ('BUILDING_COVERAGE_RATIO', 'FLOOR_AREA_RATIO')),
    CONSTRAINT ck_brp_outcome CHECK (outcome IN (
        'APPLIED', 'ALREADY_EQUAL', 'SKIPPED_EXISTING_CONFLICT', 'SKIPPED_SHARED_SCOPE',
        'SKIPPED_SOURCE_CONFLICT', 'SOURCE_MISSING'
    )),
    CONSTRAINT ck_brp_candidate_outcome CHECK (
        (candidate_id IS NULL AND outcome = 'SOURCE_MISSING')
        OR (candidate_id IS NOT NULL AND outcome <> 'SOURCE_MISSING')
    )
);

CREATE INDEX ix_brc_target_collection ON public.building_register_collection_target (collection_id, id);
CREATE INDEX ix_brc_target_pnu ON public.building_register_collection_target (pnu);
CREATE INDEX ix_bre_snapshot_collection_status ON public.building_register_endpoint_snapshot (collection_id, status);
CREATE INDEX ix_bre_snapshot_pnu_endpoint ON public.building_register_endpoint_snapshot (pnu, endpoint);
CREATE INDEX ix_brr_snapshot_page ON public.building_register_raw_page (endpoint_snapshot_id, page_no);
CREATE INDEX ix_brs_pnu ON public.building_register_record_snapshot (pnu);
CREATE INDEX ix_brs_management_key ON public.building_register_record_snapshot (mgm_bldrgst_pk);
CREATE INDEX ix_brs_parent_key ON public.building_register_record_snapshot (mgm_up_bldrgst_pk)
    WHERE mgm_up_bldrgst_pk IS NOT NULL;
CREATE INDEX ix_brcm_collection_status ON public.building_register_complex_match (collection_id, status);
CREATE INDEX ix_brcm_root_key ON public.building_register_complex_match (root_management_key)
    WHERE root_management_key IS NOT NULL;
CREATE INDEX ix_brc_candidate_match_field ON public.building_ratio_candidate (match_id, field);
CREATE INDEX ix_brp_complex_field ON public.building_ratio_projection (complex_id, field, created_at DESC);
