CREATE TABLE public.market_news_execution_aggregate_correction (
    correction_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id uuid NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT now(),
    correction_reason varchar(64) NOT NULL,
    old_completed_count integer NOT NULL,
    new_completed_count integer NOT NULL,
    old_truncated_count integer NOT NULL,
    new_truncated_count integer NOT NULL,
    old_failed_count integer NOT NULL,
    new_failed_count integer NOT NULL,
    old_skipped_budget_count integer NOT NULL,
    new_skipped_budget_count integer NOT NULL,
    old_raw_item_count integer NOT NULL,
    new_raw_item_count integer NOT NULL,
    CONSTRAINT fk_market_news_execution_aggregate_correction
        FOREIGN KEY (execution_id)
        REFERENCES public.market_news_collection_execution(execution_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_market_news_execution_aggregate_correction
        UNIQUE (execution_id, correction_reason),
    CONSTRAINT ck_market_news_execution_aggregate_correction_reason
        CHECK (correction_reason = 'DERIVED_WORK_UNIT_RECONCILIATION'),
    CONSTRAINT ck_market_news_execution_aggregate_correction_counts
        CHECK (old_completed_count >= 0
            AND new_completed_count >= 0
            AND old_truncated_count >= 0
            AND new_truncated_count >= 0
            AND old_failed_count >= 0
            AND new_failed_count >= 0
            AND old_skipped_budget_count >= 0
            AND new_skipped_budget_count >= 0
            AND old_raw_item_count >= 0
            AND new_raw_item_count >= 0)
);

WITH actual AS (
    SELECT execution.execution_id,
           count(*) FILTER (WHERE work_unit.state = 'COMPLETED')::integer
               AS completed_count,
           count(*) FILTER (WHERE work_unit.state = 'TRUNCATED')::integer
               AS truncated_count,
           count(*) FILTER (WHERE work_unit.state = 'FAILED')::integer
               AS failed_count,
           count(*) FILTER (WHERE work_unit.state = 'SKIPPED_BUDGET')::integer
               AS skipped_budget_count,
           (
               SELECT count(*)::integer
               FROM public.market_news_raw_item raw_item
               JOIN public.market_news_collection_work_unit raw_work_unit
                 ON raw_work_unit.work_unit_id = raw_item.work_unit_id
               WHERE raw_work_unit.execution_id = execution.execution_id
           ) AS raw_item_count
    FROM public.market_news_collection_execution execution
    LEFT JOIN public.market_news_collection_work_unit work_unit
      ON work_unit.execution_id = execution.execution_id
    WHERE execution.state IN ('COMPLETED', 'PARTIAL', 'FAILED')
    GROUP BY execution.execution_id
),
corrections AS (
    INSERT INTO public.market_news_execution_aggregate_correction (
        execution_id,
        correction_reason,
        old_completed_count,
        new_completed_count,
        old_truncated_count,
        new_truncated_count,
        old_failed_count,
        new_failed_count,
        old_skipped_budget_count,
        new_skipped_budget_count,
        old_raw_item_count,
        new_raw_item_count
    )
    SELECT execution.execution_id,
           'DERIVED_WORK_UNIT_RECONCILIATION',
           execution.completed_work_unit_count,
           actual.completed_count,
           execution.truncated_work_unit_count,
           actual.truncated_count,
           execution.failed_work_unit_count,
           actual.failed_count,
           execution.skipped_budget_work_unit_count,
           actual.skipped_budget_count,
           execution.raw_item_count,
           actual.raw_item_count
    FROM public.market_news_collection_execution execution
    JOIN actual ON actual.execution_id = execution.execution_id
    WHERE execution.completed_work_unit_count <> actual.completed_count
       OR execution.truncated_work_unit_count <> actual.truncated_count
       OR execution.failed_work_unit_count <> actual.failed_count
       OR execution.skipped_budget_work_unit_count <> actual.skipped_budget_count
       OR execution.raw_item_count <> actual.raw_item_count
    RETURNING execution_id,
              new_completed_count,
              new_truncated_count,
              new_failed_count,
              new_skipped_budget_count,
              new_raw_item_count
)
UPDATE public.market_news_collection_execution execution
SET completed_work_unit_count = corrections.new_completed_count,
    truncated_work_unit_count = corrections.new_truncated_count,
    failed_work_unit_count = corrections.new_failed_count,
    skipped_budget_work_unit_count = corrections.new_skipped_budget_count,
    raw_item_count = corrections.new_raw_item_count,
    bootstrap_truncated = execution.execution_type = 'BOOTSTRAP'
        AND corrections.new_truncated_count > 0
FROM corrections
WHERE execution.execution_id = corrections.execution_id;
