CREATE TABLE public.market_news_execution_failure_correction (
    correction_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id uuid NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT now(),
    correction_reason varchar(64) NOT NULL,
    old_failure_kind varchar(64) NOT NULL,
    new_failure_kind varchar(64) NOT NULL,
    CONSTRAINT fk_market_news_execution_failure_correction
        FOREIGN KEY (execution_id)
        REFERENCES public.market_news_collection_execution(execution_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_market_news_execution_failure_correction
        UNIQUE (execution_id, correction_reason),
    CONSTRAINT ck_market_news_execution_failure_correction_reason
        CHECK (correction_reason = 'PROVIDER_FAILURE_PRECEDENCE'),
    CONSTRAINT ck_market_news_execution_failure_correction_kind
        CHECK (old_failure_kind = 'DAILY_CALL_BUDGET'
            AND new_failure_kind IN ('AUTHENTICATION', 'DAILY_QUOTA'))
);

WITH actual AS (
    SELECT execution.execution_id,
           CASE
               WHEN bool_or(work_unit.failure_kind = 'AUTHENTICATION') THEN 'AUTHENTICATION'
               ELSE 'DAILY_QUOTA'
           END AS provider_failure_kind
    FROM public.market_news_collection_execution execution
    JOIN public.market_news_collection_work_unit work_unit
      ON work_unit.execution_id = execution.execution_id
    WHERE execution.state IN ('COMPLETED', 'PARTIAL', 'FAILED')
      AND execution.failure_kind = 'DAILY_CALL_BUDGET'
      AND work_unit.state = 'FAILED'
      AND work_unit.failure_kind IN ('AUTHENTICATION', 'DAILY_QUOTA')
    GROUP BY execution.execution_id
),
corrections AS (
    INSERT INTO public.market_news_execution_failure_correction (
        execution_id,
        correction_reason,
        old_failure_kind,
        new_failure_kind
    )
    SELECT execution.execution_id,
           'PROVIDER_FAILURE_PRECEDENCE',
           execution.failure_kind,
           actual.provider_failure_kind
    FROM public.market_news_collection_execution execution
    JOIN actual ON actual.execution_id = execution.execution_id
    RETURNING execution_id, new_failure_kind
)
UPDATE public.market_news_collection_execution execution
SET failure_kind = corrections.new_failure_kind
FROM corrections
WHERE execution.execution_id = corrections.execution_id;
