CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE public.map_marker_generation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status character varying(16) NOT NULL,
    source_watermark character varying(256) NOT NULL,
    complex_marker_count bigint DEFAULT 0 NOT NULL,
    region_marker_count bigint DEFAULT 0 NOT NULL,
    marker_hash character varying(64),
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    validated_at timestamp with time zone,
    activated_at timestamp with time zone,
    completed_at timestamp with time zone,
    failure_reason text,
    CONSTRAINT ck_map_marker_generation_status CHECK (
        status IN ('BUILDING', 'VALIDATED', 'ACTIVE', 'RETIRED', 'FAILED')
    ),
    CONSTRAINT ck_map_marker_generation_watermark CHECK (btrim(source_watermark) <> ''),
    CONSTRAINT ck_map_marker_generation_counts CHECK (
        complex_marker_count >= 0 AND region_marker_count >= 0
    ),
    CONSTRAINT ck_map_marker_generation_hash CHECK (
        marker_hash IS NULL OR marker_hash ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_map_marker_generation_lifecycle CHECK (
        (status = 'BUILDING'
            AND validated_at IS NULL
            AND activated_at IS NULL
            AND completed_at IS NULL
            AND failure_reason IS NULL
            AND marker_hash IS NULL)
        OR (status = 'VALIDATED'
            AND validated_at IS NOT NULL
            AND activated_at IS NULL
            AND completed_at IS NULL
            AND failure_reason IS NULL
            AND marker_hash IS NOT NULL)
        OR (status = 'ACTIVE'
            AND validated_at IS NOT NULL
            AND activated_at IS NOT NULL
            AND completed_at IS NULL
            AND failure_reason IS NULL
            AND marker_hash IS NOT NULL)
        OR (status = 'RETIRED'
            AND validated_at IS NOT NULL
            AND activated_at IS NOT NULL
            AND completed_at IS NOT NULL
            AND failure_reason IS NULL
            AND marker_hash IS NOT NULL)
        OR (status = 'FAILED'
            AND activated_at IS NULL
            AND completed_at IS NOT NULL
            AND failure_reason IS NOT NULL)
    )
);

CREATE TABLE public.map_complex_marker_projection (
    generation_id bigint NOT NULL
        REFERENCES public.map_marker_generation(id) ON DELETE CASCADE,
    marker_key character varying(96) NOT NULL,
    parcel_id bigint NOT NULL,
    complex_id bigint,
    complex_name character varying(255),
    lat double precision NOT NULL,
    lng double precision NOT NULL,
    point public.geometry(Point,4326) NOT NULL,
    latest_deal_amount bigint,
    latest_excl_area numeric(10,4),
    unit_cnt_sum bigint NOT NULL,
    building_age integer,
    ratio_members jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (generation_id, marker_key),
    CONSTRAINT ck_map_complex_marker_key CHECK (btrim(marker_key) <> ''),
    CONSTRAINT ck_map_complex_marker_coordinates CHECK (
        lat BETWEEN 33 AND 39 AND lng BETWEEN 124 AND 132
    ),
    CONSTRAINT ck_map_complex_marker_amount CHECK (
        latest_deal_amount IS NULL OR latest_deal_amount >= 0
    ),
    CONSTRAINT ck_map_complex_marker_area CHECK (
        latest_excl_area IS NULL OR latest_excl_area > 0
    ),
    CONSTRAINT ck_map_complex_marker_units CHECK (unit_cnt_sum >= 0),
    CONSTRAINT ck_map_complex_marker_age CHECK (building_age IS NULL OR building_age >= 0),
    CONSTRAINT ck_map_complex_marker_ratios CHECK (jsonb_typeof(ratio_members) = 'array'),
    CONSTRAINT ck_map_complex_marker_identity CHECK (
        marker_key = CASE
            WHEN complex_id IS NULL THEN 'parcel:' || parcel_id::text
            ELSE 'complex:' || complex_id::text
        END
    )
);

CREATE TABLE public.map_region_marker_projection (
    generation_id bigint NOT NULL
        REFERENCES public.map_marker_generation(id) ON DELETE CASCADE,
    region_id bigint NOT NULL,
    region_type character varying(32) NOT NULL,
    region_name character varying(255) NOT NULL,
    lat double precision NOT NULL,
    lng double precision NOT NULL,
    point public.geometry(Point,4326) NOT NULL,
    unit_cnt_sum bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (generation_id, region_id),
    CONSTRAINT ck_map_region_marker_type CHECK (btrim(region_type) <> ''),
    CONSTRAINT ck_map_region_marker_coordinates CHECK (
        lat BETWEEN 33 AND 39 AND lng BETWEEN 124 AND 132
    ),
    CONSTRAINT ck_map_region_marker_units CHECK (unit_cnt_sum >= 0)
);

CREATE TABLE public.map_marker_active_generation (
    singleton_id smallint PRIMARY KEY DEFAULT 1,
    generation_id bigint NOT NULL UNIQUE
        REFERENCES public.map_marker_generation(id),
    activated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_map_marker_active_singleton CHECK (singleton_id = 1)
);

CREATE INDEX ix_map_complex_marker_projection_bounds
    ON public.map_complex_marker_projection(generation_id, lat, lng);
CREATE INDEX ix_map_complex_marker_projection_point
    ON public.map_complex_marker_projection USING gist(point);
CREATE INDEX ix_map_complex_marker_projection_filters
    ON public.map_complex_marker_projection(
        generation_id,
        latest_deal_amount,
        latest_excl_area,
        unit_cnt_sum,
        building_age
    );
CREATE INDEX ix_map_region_marker_projection_bounds
    ON public.map_region_marker_projection(generation_id, region_type, lat, lng);
CREATE INDEX ix_map_region_marker_projection_point
    ON public.map_region_marker_projection USING gist(point);

CREATE FUNCTION public.activate_map_marker_generation()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    candidate_status character varying(16);
BEGIN
    SELECT status
    INTO candidate_status
    FROM public.map_marker_generation
    WHERE id = NEW.generation_id
    FOR UPDATE;

    IF candidate_status IS DISTINCT FROM 'VALIDATED'
        AND candidate_status IS DISTINCT FROM 'ACTIVE'
        AND candidate_status IS DISTINCT FROM 'RETIRED' THEN
        RAISE EXCEPTION 'map marker generation % is not validated', NEW.generation_id;
    END IF;

    IF TG_OP = 'UPDATE' AND OLD.generation_id <> NEW.generation_id THEN
        UPDATE public.map_marker_generation
        SET status = 'RETIRED',
            completed_at = now()
        WHERE id = OLD.generation_id
          AND status = 'ACTIVE';
    END IF;

    UPDATE public.map_marker_generation
    SET status = 'ACTIVE',
        activated_at = now(),
        completed_at = NULL
    WHERE id = NEW.generation_id
      AND status IN ('VALIDATED', 'RETIRED');

    NEW.activated_at := now();
    RETURN NEW;
END
$function$;

CREATE TRIGGER trg_activate_map_marker_generation
BEFORE INSERT OR UPDATE OF generation_id
ON public.map_marker_active_generation
FOR EACH ROW
EXECUTE FUNCTION public.activate_map_marker_generation();
