spring.datasource.url=${DB_JDBC_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.locations=${SPRING_FLYWAY_LOCATIONS:classpath:db/migration/api,classpath:db/seed/local}
spring.flyway.clean-disabled=true
