spring.application.name=home-search-api
spring.profiles.default=local
spring.flyway.locations=classpath:db/migration/api
apis.data.base-url=https://apis.data.go.kr
apis.data.apt-service-key=${APT_SERVICE_KEY:}
apis.data.apt-title-path=/1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev
apis.data.apt-num-of-rows=1000
apis.data.connect-timeout-millis=5000
apis.data.read-timeout-millis=5000
