spring:
  datasource:
    url: "${DB_JDBC_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: "${SPRING_FLYWAY_LOCATIONS:classpath:db/migration/api,classpath:db/seed/local}"
    clean-disabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

home:
  coordinate-source:
    db:
      jdbc-url: "${COORDINATE_SOURCE_DB_JDBC_URL:}"
      username: "${COORDINATE_SOURCE_DB_USERNAME:${DB_USERNAME}}"
      password: "${COORDINATE_SOURCE_DB_PASSWORD:${DB_PASSWORD}}"
