CREATE SCHEMA IF NOT EXISTS admin;

CREATE TABLE admin.migration_ownership (
    owner_name varchar(100) PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT migration_ownership_admin_service CHECK (owner_name = 'admin-service')
);
INSERT INTO admin.migration_ownership(owner_name) VALUES ('admin-service');

CREATE TABLE admin.admin_account (
    id uuid PRIMARY KEY,
    login_id varchar(100) NOT NULL UNIQUE,
    display_name varchar(100) NOT NULL,
    password_hash varchar(100) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    failed_login_count integer NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
    locked_until timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE admin.admin_role (code varchar(50) PRIMARY KEY);
CREATE TABLE admin.admin_permission (code varchar(100) PRIMARY KEY);
CREATE TABLE admin.admin_account_role (
    account_id uuid REFERENCES admin.admin_account(id) ON DELETE CASCADE,
    role_code varchar(50) REFERENCES admin.admin_role(code),
    PRIMARY KEY (account_id, role_code)
);
CREATE TABLE admin.admin_role_permission (
    role_code varchar(50) REFERENCES admin.admin_role(code) ON DELETE CASCADE,
    permission_code varchar(100) REFERENCES admin.admin_permission(code),
    PRIMARY KEY (role_code, permission_code)
);
CREATE TABLE admin.admin_security_audit_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_account_id uuid,
    target_account_id uuid,
    event_type varchar(100) NOT NULL,
    request_id varchar(100),
    success boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO admin.admin_role(code) VALUES ('VIEWER'), ('OPERATOR'), ('ADMIN');
INSERT INTO admin.admin_permission(code) VALUES
 ('COORDINATE_READ'), ('COORDINATE_WRITE'), ('METADATA_READ'), ('METADATA_RETRY'),
 ('METADATA_HOLD'), ('METADATA_ALIAS_MANAGE'), ('ADMIN_ACCOUNT_MANAGE'), ('ADMIN_AUDIT_READ');
INSERT INTO admin.admin_role_permission(role_code, permission_code)
SELECT 'VIEWER', code FROM admin.admin_permission WHERE code IN ('COORDINATE_READ', 'METADATA_READ');
INSERT INTO admin.admin_role_permission(role_code, permission_code)
SELECT 'OPERATOR', code FROM admin.admin_permission WHERE code NOT LIKE 'ADMIN_%';
INSERT INTO admin.admin_role_permission(role_code, permission_code)
SELECT 'ADMIN', code FROM admin.admin_permission;

CREATE TABLE admin.spring_session (
    primary_id char(36) NOT NULL PRIMARY KEY,
    session_id char(36) NOT NULL UNIQUE,
    creation_time bigint NOT NULL,
    last_access_time bigint NOT NULL,
    max_inactive_interval integer NOT NULL,
    expiry_time bigint NOT NULL,
    principal_name varchar(100)
);
CREATE INDEX spring_session_ix1 ON admin.spring_session(last_access_time);
CREATE INDEX spring_session_ix2 ON admin.spring_session(expiry_time);
CREATE INDEX spring_session_ix3 ON admin.spring_session(principal_name);
CREATE TABLE admin.spring_session_attributes (
    session_primary_id char(36) NOT NULL REFERENCES admin.spring_session(primary_id) ON DELETE CASCADE,
    attribute_name varchar(200) NOT NULL,
    attribute_bytes bytea NOT NULL,
    PRIMARY KEY (session_primary_id, attribute_name)
);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'home_search_admin_runtime') THEN
        GRANT USAGE ON SCHEMA admin TO home_search_admin_runtime;
        GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA admin TO home_search_admin_runtime;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA admin TO home_search_admin_runtime;
        ALTER DEFAULT PRIVILEGES IN SCHEMA admin
            GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO home_search_admin_runtime;
        ALTER DEFAULT PRIVILEGES IN SCHEMA admin
            GRANT USAGE, SELECT ON SEQUENCES TO home_search_admin_runtime;
        REVOKE ALL PRIVILEGES ON TABLE admin.flyway_schema_history FROM home_search_admin_runtime;
    END IF;
END $$;
