pluginManagement { repositories { gradlePluginPortal(); mavenCentral() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { mavenCentral() } }
rootProject.name = 'home-search-user-service'
include 'core', 'app'
includeBuild('../../../libs/security-jwt-core') {
    dependencySubstitution { substitute module('com.home:security-jwt-core') using project(':') }
}
includeBuild('../../../libs/user-auth-contract') {
    dependencySubstitution { substitute module('com.home:user-auth-contract') using project(':') }
}
