import {createServer,type ServerResponse} from 'node:http'; import {readFileSync} from 'node:fs';
import {renderLegalDocument,renderSeoDocument} from '../src/seo/seoDocument'; import {buildComplexSitemaps,buildPagesSitemap,buildRegionSitemap,buildSitemapIndex} from '../src/seo/sitemap'; import type {SeoComplexData,SeoPage,SeoRegionData} from '../src/seo/types'; import type {LegalPageKind} from '../src/legal/LegalPage';
const port=positiveInteger(process.env.PORT,3000),origin=normalizedOrigin(process.env.HOME_SEO_CANONICAL_ORIGIN??'http://localhost:8080'),backend=normalizedOrigin(process.env.HOME_SEO_PROPERTY_API_BASE_URL??'http://property-api:8080'),mode=parseMode(process.env.HOME_SEO_INDEX_MODE??'PILOT'),pageTtl=duration(process.env.HOME_SEO_PAGE_CACHE_TTL??'15m'),sitemapTtl=duration(process.env.HOME_SEO_SITEMAP_CACHE_TTL??'6h'),staleIfError=duration(process.env.HOME_SEO_STALE_IF_ERROR??'24h'),template=readTemplate(process.env.HOME_SEO_CLIENT_INDEX??'/app/index.html');let sitemapCache:CacheEntry<Map<string,string>>|undefined;
createServer(async(request,response)=>{const path=new URL(request.url??'/',origin).pathname;if(path==='/health')return send(response,200,'text/plain; charset=utf-8','ok\n');if(path==='/robots.txt')return send(response,200,'text/plain; charset=utf-8',robots());if(path==='/sitemap.xml'||path.startsWith('/sitemaps/'))return sitemap(path,response);const legal=legalKind(path);if(legal)return sendHtml(response,200,renderLegalDocument(legal,origin,template),true);const match=path.match(/^\/(complexes|regions)\/([1-9][0-9]*)$/u);if(match)return landing(match[1]!,Number(match[2]),response);return errorPage(response,404,'페이지를 찾을 수 없습니다.');}).listen(port,'0.0.0.0');
async function landing(kind:string,id:number,response:ServerResponse){if(!Number.isSafeInteger(id)||mode==='OFF')return errorPage(response,mode==='OFF'?503:404,'페이지를 제공할 수 없습니다.');const key=`${kind}:${id}`,cached=pageCache.get(key);if(cached)return sendHtml(response,200,cached.value,cached.indexable);try{const endpoint=kind==='complexes'?`complexes/${id}`:`regions/${id}?mode=${mode}`,data=await backendJson<SeoComplexData|SeoRegionData>(`/internal/v1/seo/${endpoint}`),page={kind:kind==='complexes'?'complex':'region',canonicalOrigin:origin,data} as SeoPage,html=renderSeoDocument(page,template);pageCache.set(key,{value:html,expiresAt:Date.now()+pageTtl,indexable:data.indexable});return sendHtml(response,200,html,data.indexable);}catch(error){return errorPage(response,error instanceof BackendNotFound?404:503,error instanceof BackendNotFound?'페이지를 찾을 수 없습니다.':'잠시 후 다시 시도해 주세요.');}}
async function sitemap(path:string,response:ServerResponse){try{const bundle=await sitemapBundle(),xml=bundle.get(path);if(xml==null)return errorPage(response,404,'사이트맵을 찾을 수 없습니다.');return send(response,200,'application/xml; charset=utf-8',xml);}catch{if(sitemapCache&&Date.now()<=sitemapCache.staleUntil){const xml=sitemapCache.value.get(path);if(xml!=null)return send(response,200,'application/xml; charset=utf-8',xml);}return errorPage(response,503,'사이트맵을 준비하지 못했습니다.');}}
async function sitemapBundle(){if(sitemapCache&&Date.now()<=sitemapCache.expiresAt)return sitemapCache.value;const ids:number[]=[];let afterId=0,more=true;while(more){const page=await backendJson<Array<{complexId:number}>>(`/internal/v1/seo/catalog/complexes?mode=${mode}&afterId=${afterId}&limit=10000`);if(page.length===0)break;ids.push(...page.map((item)=>item.complexId));afterId=Math.max(...page.map((item)=>item.complexId));more=mode==='ALL'&&page.length===10000;}const regions=await backendJson<Array<{regionId:number}>>(`/internal/v1/seo/catalog/regions?mode=${mode}`),complexMaps=buildComplexSitemaps(origin,ids),value=new Map<string,string>();value.set('/sitemap.xml',buildSitemapIndex(origin,complexMaps.length));value.set('/sitemaps/pages.xml',buildPagesSitemap(origin));value.set('/sitemaps/regions.xml',buildRegionSitemap(origin,regions.map((item)=>item.regionId)));complexMaps.forEach((xml,index)=>value.set(`/sitemaps/complexes-${String(index+1).padStart(4,'0')}.xml`,xml));sitemapCache={value,expiresAt:Date.now()+sitemapTtl,staleUntil:Date.now()+sitemapTtl+staleIfError};return value;}
async function backendJson<T>(path:string):Promise<T>{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),5000);try{const response=await fetch(`${backend}${path}`,{signal:controller.signal,headers:{Accept:'application/json'}});if(response.status===404)throw new BackendNotFound();if(!response.ok)throw new Error(`backend status ${response.status}`);return await response.json() as T;}finally{clearTimeout(timeout);}}
function robots(){return `User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /internal/\nDisallow: /auth/\nDisallow: /my/\nDisallow: /insights/\nSitemap: ${origin}/sitemap.xml\n`;}
function sendHtml(response:ServerResponse,status:number,body:string,indexable:boolean){response.setHeader('X-Robots-Tag',indexable?'index, follow':'noindex, follow');send(response,status,'text/html; charset=utf-8',body);}function errorPage(response:ServerResponse,status:404|503,message:string){response.setHeader('X-Robots-Tag','noindex, nofollow');if(status===503)response.setHeader('Retry-After','60');send(response,status,'text/html; charset=utf-8',`<!doctype html><html lang="ko"><head><meta name="robots" content="noindex"><title>${status} | 홈서치</title></head><body><main><h1>${status}</h1><p>${message}</p></main></body></html>`);}function send(response:ServerResponse,status:number,contentType:string,body:string){response.statusCode=status;response.setHeader('Content-Type',contentType);response.setHeader('Cache-Control','no-cache');response.end(body);}
function normalizedOrigin(value:string){return new URL(value).origin;}function positiveInteger(value:string|undefined,fallback:number){const parsed=Number(value);return Number.isSafeInteger(parsed)&&parsed>0?parsed:fallback;}function parseMode(value:string){if(value==='OFF'||value==='PILOT'||value==='ALL')return value;throw new Error('HOME_SEO_INDEX_MODE must be OFF, PILOT, or ALL');}function duration(value:string){const match=value.match(/^([1-9][0-9]*)(s|m|h)$/u);if(!match)throw new Error(`invalid duration: ${value}`);return Number(match[1])*({s:1000,m:60000,h:3600000}[match[2]!]!);}function readTemplate(path:string){try{return readFileSync(path,'utf8');}catch{return undefined;}}class BackendNotFound extends Error{}type CacheEntry<T>={value:T;expiresAt:number;staleUntil:number};
function legalKind(path:string):LegalPageKind|undefined{return path==='/privacy'?'privacy':path==='/terms'?'terms':path==='/about'?'about':undefined;}
class LruCache<T>{private readonly values=new Map<string,CacheEntry<T>&{indexable:boolean}>();constructor(private readonly maximum:number){}get(key:string){const entry=this.values.get(key);if(!entry||entry.expiresAt<Date.now()){this.values.delete(key);return undefined;}this.values.delete(key);this.values.set(key,entry);return entry;}set(key:string,entry:{value:T;expiresAt:number;indexable:boolean}){this.values.delete(key);this.values.set(key,{...entry,staleUntil:entry.expiresAt});if(this.values.size>this.maximum)this.values.delete(this.values.keys().next().value!);}}
const pageCache=new LruCache<string>(5000);
