spring:
  main:
    web-application-type: none
  flyway:
    enabled: false
  datasource:
    url: ${ADMIN_MIGRATION_DB_JDBC_URL}
    username: ${ADMIN_MIGRATION_DB_USERNAME}
    password: ${ADMIN_MIGRATION_DB_PASSWORD}
