flyway.locations=filesystem:/flyway/sql
flyway.schemas=public,reference,batch
flyway.defaultSchema=public
flyway.table=flyway_schema_history
flyway.cleanDisabled=true
flyway.validateMigrationNaming=true
