#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NEWS_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

export HOME_NEWS_ENABLED="${HOME_NEWS_ENABLED:-true}"
export HOME_NEWS_RUN_ONCE_ENABLED="${HOME_NEWS_RUN_ONCE_ENABLED:-false}"
export HOME_NEWS_RESEARCH_SEED_ENABLED="${HOME_NEWS_RESEARCH_SEED_ENABLED:-true}"
export HOME_NEWS_RESEARCH_SEED_MODE="${HOME_NEWS_RESEARCH_SEED_MODE:-GENERATE_NOTES}"

if [[ "${HOME_NEWS_RESEARCH_SEED_MODE}" == "GENERATE_NOTES" && -z "${OPENAI_API_KEY:-}" ]]; then
  echo "OPENAI_API_KEY is required for GENERATE_NOTES. Export it before running this script." >&2
  exit 2
fi

export HOME_NEWS_RESEARCH_SEED_MODEL="${HOME_NEWS_RESEARCH_SEED_MODEL:-gpt-5.4-mini}"
export HOME_NEWS_RESEARCH_SEED_PERIOD_START="${HOME_NEWS_RESEARCH_SEED_PERIOD_START:-2020-06-01}"
export HOME_NEWS_RESEARCH_SEED_PERIOD_END="${HOME_NEWS_RESEARCH_SEED_PERIOD_END:-2020-06-30}"
export HOME_NEWS_RESEARCH_SEED_MAX_REQUESTS_PER_RUN="${HOME_NEWS_RESEARCH_SEED_MAX_REQUESTS_PER_RUN:-2}"
export HOME_NEWS_RESEARCH_SEED_TARGET_CANDIDATES_PER_BUCKET="${HOME_NEWS_RESEARCH_SEED_TARGET_CANDIDATES_PER_BUCKET:-10}"
export HOME_NEWS_RESEARCH_SEED_MIN_REVIEW_NOTES_PER_RUN="${HOME_NEWS_RESEARCH_SEED_MIN_REVIEW_NOTES_PER_RUN:-3}"
export HOME_NEWS_RESEARCH_SEED_REASONING_EFFORT="${HOME_NEWS_RESEARCH_SEED_REASONING_EFFORT:-low}"
export HOME_NEWS_RESEARCH_SEED_MAX_OUTPUT_TOKENS="${HOME_NEWS_RESEARCH_SEED_MAX_OUTPUT_TOKENS:-8192}"
export HOME_NEWS_RESEARCH_SEED_MAX_TOOL_CALLS="${HOME_NEWS_RESEARCH_SEED_MAX_TOOL_CALLS:-3}"
export HOME_NEWS_RESEARCH_SEED_OUTPUT_DIR="${HOME_NEWS_RESEARCH_SEED_OUTPUT_DIR:-news-research-seed/obsidian}"
export HOME_NEWS_RESEARCH_SEED_CSV_INPUT_DIR="${HOME_NEWS_RESEARCH_SEED_CSV_INPUT_DIR:-apps/news/local-input/historical-news-csv}"
export HOME_NEWS_RESEARCH_SEED_CSV_SHORTLIST_LIMIT="${HOME_NEWS_RESEARCH_SEED_CSV_SHORTLIST_LIMIT:-20}"
export SPRING_DATASOURCE_URL="${SPRING_DATASOURCE_URL:-jdbc:postgresql://localhost:15432/home_search}"
export SPRING_DATASOURCE_USERNAME="${SPRING_DATASOURCE_USERNAME:-home_search}"
export SPRING_DATASOURCE_PASSWORD="${SPRING_DATASOURCE_PASSWORD:-home_search_local_password}"

echo "Running historical research seed smoke:"
echo "  mode=${HOME_NEWS_RESEARCH_SEED_MODE}"
echo "  model=${HOME_NEWS_RESEARCH_SEED_MODEL}"
echo "  period=${HOME_NEWS_RESEARCH_SEED_PERIOD_START}..${HOME_NEWS_RESEARCH_SEED_PERIOD_END}"
echo "  max_requests=${HOME_NEWS_RESEARCH_SEED_MAX_REQUESTS_PER_RUN}"
echo "  target_candidates=${HOME_NEWS_RESEARCH_SEED_TARGET_CANDIDATES_PER_BUCKET}"
echo "  min_review_notes=${HOME_NEWS_RESEARCH_SEED_MIN_REVIEW_NOTES_PER_RUN}"
echo "  reasoning_effort=${HOME_NEWS_RESEARCH_SEED_REASONING_EFFORT}"
echo "  max_output_tokens=${HOME_NEWS_RESEARCH_SEED_MAX_OUTPUT_TOKENS}"
echo "  max_tool_calls=${HOME_NEWS_RESEARCH_SEED_MAX_TOOL_CALLS}"
echo "  csv_input_dir=${HOME_NEWS_RESEARCH_SEED_CSV_INPUT_DIR}"
echo "  csv_shortlist_limit=${HOME_NEWS_RESEARCH_SEED_CSV_SHORTLIST_LIMIT}"
echo "  output_dir=${HOME_NEWS_RESEARCH_SEED_OUTPUT_DIR}"
echo "  run_once=${HOME_NEWS_RUN_ONCE_ENABLED}"

cd "${NEWS_DIR}"
exec gradle bootRun
