package com.home.infrastructure.persistence.ingest;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class JdbcPostgresTestSupportResetTest extends JdbcPostgresTestSupport {

	private static final String MARKER_TABLE = "test_reset_marker";

	@Test
	@Order(1)
	@DisplayName("persistence test support는 테스트가 만든 테이블을 다음 테스트까지 보존한다")
	void createsMarkerTableAndRow() {
		jdbcClient.sql("""
			CREATE TABLE IF NOT EXISTS test_reset_marker (
			    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			    name VARCHAR(64) NOT NULL
			)
			""").update();
		jdbcClient.sql("INSERT INTO test_reset_marker (name) VALUES ('dirty-row')").update();

		assertThat(markerTableExists()).isTrue();
		assertThat(markerRowCount()).isEqualTo(1L);
	}

	@Test
	@Order(2)
	@DisplayName("persistence test support는 스키마를 다시 만들지 않고 데이터만 비운다")
	void preservesMarkerTableAndClearsRows() {
		assertThat(markerTableExists()).isTrue();
		assertThat(markerRowCount()).isZero();

		jdbcClient.sql("DROP TABLE test_reset_marker").update();
	}

	private boolean markerTableExists() {
		return Boolean.TRUE.equals(jdbcClient.sql("""
			SELECT EXISTS (
			    SELECT 1
			    FROM information_schema.tables
			    WHERE table_schema = 'public'
			      AND table_name = :tableName
			)
			""")
			.param("tableName", MARKER_TABLE)
			.query(Boolean.class)
			.single());
	}

	private long markerRowCount() {
		return jdbcClient.sql("SELECT count(*) FROM test_reset_marker")
			.query(Long.class)
			.single();
	}
}
