ALTER TABLE complex
    DROP CONSTRAINT ck_complex_metadata_status;

ALTER TABLE complex
    ADD CONSTRAINT ck_complex_metadata_status
    CHECK (metadata_status IN ('PENDING', 'RESOLVED', 'PARTIAL', 'AMBIGUOUS', 'UNAVAILABLE', 'FAILED'));

ALTER TABLE complex
    ADD COLUMN metadata_attempts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN metadata_failure_kind VARCHAR(24),
    ADD COLUMN metadata_next_attempt_at TIMESTAMPTZ;

ALTER TABLE complex
    ADD CONSTRAINT ck_complex_metadata_failure_kind
    CHECK (
        metadata_failure_kind IS NULL
        OR metadata_failure_kind IN ('TRANSIENT', 'PERMANENT', 'SOURCE_MISSING', 'INPUT_INSUFFICIENT', 'AMBIGUOUS')
    );

UPDATE complex
SET metadata_status = CASE
        WHEN dong_cnt > 0 AND unit_cnt > 0 AND use_date IS NOT NULL THEN 'RESOLVED'
        WHEN dong_cnt IS NOT NULL
          OR unit_cnt IS NOT NULL
          OR plat_area IS NOT NULL
          OR arch_area IS NOT NULL
          OR tot_area IS NOT NULL
          OR bc_rat IS NOT NULL
          OR vl_rat IS NOT NULL
          OR use_date IS NOT NULL THEN 'PARTIAL'
        ELSE metadata_status
    END
WHERE metadata_status = 'RESOLVED';

CREATE INDEX ix_complex_metadata_due
    ON complex (metadata_next_attempt_at)
    WHERE metadata_next_attempt_at IS NOT NULL;

CREATE TABLE complex_metadata_enrichment_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complex_id BIGINT NOT NULL REFERENCES complex(id) ON DELETE CASCADE,
    attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
    status VARCHAR(16) NOT NULL CHECK (status IN ('RESOLVED', 'PARTIAL', 'AMBIGUOUS', 'UNAVAILABLE', 'FAILED')),
    source VARCHAR(32),
    failure_kind VARCHAR(24) CHECK (
        failure_kind IS NULL
        OR failure_kind IN ('TRANSIENT', 'PERMANENT', 'SOURCE_MISSING', 'INPUT_INSUFFICIENT', 'AMBIGUOUS')
    ),
    failure_reason TEXT,
    next_attempt_at TIMESTAMPTZ,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_cmea_complex
    ON complex_metadata_enrichment_attempt (complex_id, observed_at DESC);
