CREATE TABLE building_footprint_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pnu VARCHAR(19) NOT NULL CHECK (pnu ~ '^[0-9]{19}$'),
    building_name VARCHAR(255),
    dong_name VARCHAR(255),
    main_purps_cd VARCHAR(32),
    source_building_key VARCHAR(128) NOT NULL,
    centroid_lat NUMERIC(10, 7) NOT NULL CHECK (centroid_lat BETWEEN 33 AND 39),
    centroid_lng NUMERIC(10, 7) NOT NULL CHECK (centroid_lng BETWEEN 124 AND 132),
    geom geometry(MultiPolygon, 4326),
    source VARCHAR(32) NOT NULL,
    snapshot_version VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_building_footprint_source_key UNIQUE (source, snapshot_version, source_building_key)
);

CREATE INDEX ix_building_footprint_snapshot_pnu
    ON building_footprint_snapshot (pnu);

CREATE INDEX ix_building_footprint_snapshot_geom
    ON building_footprint_snapshot USING GIST (geom);

CREATE TABLE complex_coordinate_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES parcel(id) ON DELETE CASCADE,
    pnu VARCHAR(19) NOT NULL CHECK (pnu ~ '^[0-9]{19}$'),
    status VARCHAR(16) NOT NULL CHECK (
        status IN ('PENDING', 'RESOLVED', 'AMBIGUOUS', 'UNAVAILABLE', 'FAILED', 'SKIPPED')
    ),
    relation_type VARCHAR(32) CHECK (
        relation_type IS NULL OR relation_type IN ('SINGLE', 'CONCURRENT', 'REDEVELOPED', 'UNKNOWN')
    ),
    relation_confidence VARCHAR(16) CHECK (
        relation_confidence IS NULL OR relation_confidence IN ('HIGH', 'MEDIUM', 'LOW', 'NONE')
    ),
    reason TEXT,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_complex_coordinate_case_parcel UNIQUE (parcel_id)
);

CREATE INDEX ix_complex_coordinate_case_status
    ON complex_coordinate_case (status, id);

CREATE TABLE complex_building_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complex_id BIGINT NOT NULL REFERENCES complex(id) ON DELETE CASCADE,
    building_footprint_id BIGINT REFERENCES building_footprint_snapshot(id) ON DELETE SET NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('RESOLVED', 'AMBIGUOUS', 'UNAVAILABLE', 'FAILED')),
    confidence INTEGER NOT NULL DEFAULT 0 CHECK (confidence BETWEEN 0 AND 100),
    reason TEXT,
    source VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_complex_building_link_resolved
    ON complex_building_link (complex_id, building_footprint_id)
    WHERE building_footprint_id IS NOT NULL;

CREATE INDEX ix_complex_building_link_complex
    ON complex_building_link (complex_id, status);

CREATE TABLE complex_display_coordinate (
    complex_id BIGINT PRIMARY KEY REFERENCES complex(id) ON DELETE CASCADE,
    building_footprint_id BIGINT REFERENCES building_footprint_snapshot(id) ON DELETE SET NULL,
    latitude NUMERIC(10, 7) NOT NULL CHECK (latitude BETWEEN 33 AND 39),
    longitude NUMERIC(10, 7) NOT NULL CHECK (longitude BETWEEN 124 AND 132),
    coordinate_source VARCHAR(32) NOT NULL CHECK (
        coordinate_source IN ('BUILDING_FOOTPRINT', 'PARCEL_FALLBACK')
    ),
    confidence INTEGER NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    reason TEXT,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
