ALTER TABLE complex_coordinate_case
    DROP CONSTRAINT IF EXISTS complex_coordinate_case_relation_type_check;

ALTER TABLE complex_coordinate_case
    ADD CONSTRAINT ck_complex_coordinate_case_relation_type
    CHECK (
        relation_type IS NULL
        OR relation_type IN ('SINGLE', 'CONCURRENT', 'REDEVELOPED', 'MASTER_UPDATE', 'UNRELATED', 'UNKNOWN')
    );

CREATE TABLE complex_relation_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_key VARCHAR(160) NOT NULL,
    parcel_id BIGINT NOT NULL REFERENCES parcel(id) ON DELETE CASCADE,
    pnu VARCHAR(19) NOT NULL CHECK (pnu ~ '^[0-9]{19}$'),
    relation_type VARCHAR(32) NOT NULL CHECK (
        relation_type IN ('SINGLE', 'CONCURRENT', 'REDEVELOPED', 'MASTER_UPDATE', 'UNRELATED', 'UNKNOWN')
    ),
    relation_confidence VARCHAR(16) NOT NULL CHECK (
        relation_confidence IN ('HIGH', 'MEDIUM', 'LOW', 'NONE')
    ),
    reason TEXT,
    classifier_version VARCHAR(64) NOT NULL,
    evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_complex_relation_case_key
    ON complex_relation_case (case_key);

CREATE INDEX ix_complex_relation_case_parcel
    ON complex_relation_case (parcel_id, id);

CREATE INDEX ix_complex_relation_case_type
    ON complex_relation_case (relation_type, relation_confidence, id);

CREATE TABLE complex_relation_case_complex (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES complex_relation_case(id) ON DELETE CASCADE,
    complex_id BIGINT NOT NULL,
    complex_pk VARCHAR(64) NOT NULL,
    apt_seq VARCHAR(64),
    name VARCHAR(255) NOT NULL,
    first_deal DATE,
    last_deal DATE,
    trade_count BIGINT NOT NULL CHECK (trade_count >= 0),
    use_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_complex_relation_case_complex UNIQUE (case_id, complex_id)
);

CREATE INDEX ix_complex_relation_case_complex_case
    ON complex_relation_case_complex (case_id, id);
