CREATE TABLE parcel_coordinate_override (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pnu VARCHAR(19) NOT NULL CHECK (pnu ~ '^[0-9]{19}$'),
    apt_seq VARCHAR(64),
    apt_name VARCHAR(255),
    address_text TEXT,
    latitude NUMERIC(10, 7) NOT NULL CHECK (latitude BETWEEN 33 AND 39),
    longitude NUMERIC(10, 7) NOT NULL CHECK (longitude BETWEEN 124 AND 132),
    source VARCHAR(32) NOT NULL CHECK (
        source IN ('MANUAL', 'VWORLD_ADDRESS_SEARCH', 'LATEST_SHP')
    ),
    confidence VARCHAR(16) NOT NULL CHECK (
        confidence IN ('HIGH', 'LOW')
    ),
    status VARCHAR(16) NOT NULL CHECK (
        status IN ('CANDIDATE', 'APPROVED', 'REJECTED')
    ),
    reason TEXT,
    source_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    approved_by VARCHAR(128),
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_parcel_coordinate_override_approved_high_confidence
        CHECK (status <> 'APPROVED' OR confidence = 'HIGH'),
    CONSTRAINT ck_parcel_coordinate_override_approved_at
        CHECK (status <> 'APPROVED' OR approved_at IS NOT NULL)
);

CREATE UNIQUE INDEX uq_parcel_coordinate_override_approved_pnu
    ON parcel_coordinate_override (pnu)
    WHERE status = 'APPROVED';

CREATE INDEX ix_parcel_coordinate_override_status_pnu
    ON parcel_coordinate_override (status, pnu, id);
