CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE region (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES region (id),
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    region_type VARCHAR(32) NOT NULL,
    center_lat NUMERIC(10, 7),
    center_lng NUMERIC(10, 7),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE parcel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT REFERENCES region (id),
    pnu VARCHAR(32) NOT NULL UNIQUE,
    address TEXT,
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    geom geometry(MultiPolygon, 4326),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_parcel_region_id ON parcel (region_id);
CREATE INDEX ix_parcel_geom ON parcel USING GIST (geom);

CREATE TABLE complex (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id BIGINT NOT NULL REFERENCES parcel (id),
    complex_pk VARCHAR(64) NOT NULL UNIQUE,
    apt_seq VARCHAR(64),
    name VARCHAR(255) NOT NULL,
    trade_name VARCHAR(255),
    dong_cnt INTEGER,
    unit_cnt INTEGER,
    plat_area NUMERIC(14, 2),
    arch_area NUMERIC(14, 2),
    tot_area NUMERIC(14, 2),
    bc_rat NUMERIC(6, 2),
    vl_rat NUMERIC(6, 2),
    use_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_complex_parcel_id ON complex (parcel_id);
CREATE INDEX ix_complex_apt_seq ON complex (apt_seq);

CREATE TABLE raw_trade_ingest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(32) NOT NULL,
    source_key VARCHAR(255) NOT NULL,
    lawd_cd VARCHAR(16) NOT NULL,
    deal_ymd VARCHAR(8) NOT NULL,
    page_no INTEGER,
    payload TEXT,
    payload_hash VARCHAR(128),
    status VARCHAR(32) NOT NULL CHECK (
        status IN ('RECEIVED', 'NORMALIZED', 'DUPLICATE', 'MATCH_FAILED', 'PARSE_FAILED', 'SKIPPED_INVALID')
    ),
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ
);

CREATE INDEX ix_raw_trade_ingest_status ON raw_trade_ingest (status, id);
CREATE INDEX ix_raw_trade_ingest_source_key ON raw_trade_ingest (source, source_key);

CREATE SEQUENCE trade_id_seq;

CREATE TABLE trade (
    id BIGINT NOT NULL DEFAULT nextval('trade_id_seq'),
    complex_id BIGINT NOT NULL REFERENCES complex (id),
    deal_date DATE NOT NULL,
    deal_amount BIGINT NOT NULL CHECK (deal_amount > 0),
    floor INTEGER,
    excl_area NUMERIC(10, 2),
    apt_dong VARCHAR(255),
    source VARCHAR(32) NOT NULL,
    source_key VARCHAR(255) NOT NULL,
    complex_pk VARCHAR(64) NOT NULL,
    apt_seq VARCHAR(64),
    raw_ingest_id BIGINT NOT NULL REFERENCES raw_trade_ingest (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_trade_id_deal_date UNIQUE (id, deal_date)
) PARTITION BY RANGE (deal_date);

DO $$
DECLARE
    partition_year INTEGER;
BEGIN
    FOR partition_year IN 2006..2030 LOOP
        EXECUTE format(
            'CREATE TABLE %I PARTITION OF trade FOR VALUES FROM (%L) TO (%L)',
            'trade_' || partition_year,
            make_date(partition_year, 1, 1),
            make_date(partition_year + 1, 1, 1)
        );
    END LOOP;
END $$;

CREATE TABLE trade_default PARTITION OF trade DEFAULT;

CREATE UNIQUE INDEX uq_trade_fallback_identity
    ON trade (complex_id, deal_date, floor, excl_area, deal_amount) NULLS NOT DISTINCT;

CREATE INDEX ix_trade_complex_latest ON trade (complex_id, deal_date DESC, id DESC);
CREATE INDEX ix_trade_raw_ingest_id ON trade (raw_ingest_id);
CREATE INDEX ix_trade_source_key ON trade (source, source_key);

CREATE TABLE trade_source_key_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(32) NOT NULL,
    source_key VARCHAR(255) NOT NULL,
    raw_ingest_id BIGINT NOT NULL REFERENCES raw_trade_ingest (id),
    trade_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_trade_source_key_registry UNIQUE (source, source_key)
);

CREATE INDEX ix_trade_source_key_registry_raw ON trade_source_key_registry (raw_ingest_id);
