CREATE TABLE rtms_backfill_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_key VARCHAR(128) NOT NULL UNIQUE,
    source VARCHAR(32) NOT NULL DEFAULT 'RTMS',
    deal_ymd_from VARCHAR(6) NOT NULL,
    deal_ymd_to VARCHAR(6) NOT NULL,
    lawd_code_source VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL CHECK (status IN ('PLANNED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED')),
    total_chunk_count INTEGER NOT NULL CHECK (total_chunk_count >= 0),
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

CREATE TABLE rtms_backfill_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES rtms_backfill_job (id) ON DELETE CASCADE,
    lawd_cd VARCHAR(16) NOT NULL,
    deal_ymd VARCHAR(6) NOT NULL,
    status VARCHAR(32) NOT NULL CHECK (
        status IN ('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'BLOCKED', 'SKIPPED')
    ),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    max_attempt_count INTEGER NOT NULL DEFAULT 3 CHECK (max_attempt_count > 0),
    last_run_id BIGINT REFERENCES rtms_ingest_run (id),
    last_failure_reason TEXT,
    locked_by VARCHAR(128),
    locked_at TIMESTAMPTZ,
    locked_until TIMESTAMPTZ,
    heartbeat_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (job_id, lawd_cd, deal_ymd)
);

CREATE TABLE rtms_backfill_chunk_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id BIGINT NOT NULL REFERENCES rtms_backfill_chunk (id) ON DELETE CASCADE,
    run_id BIGINT NOT NULL REFERENCES rtms_ingest_run (id),
    attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
    worker_id VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (chunk_id, run_id)
);

CREATE INDEX ix_rtms_backfill_chunk_next
    ON rtms_backfill_chunk (job_id, status, deal_ymd, lawd_cd);

CREATE INDEX ix_rtms_backfill_chunk_lawd_month
    ON rtms_backfill_chunk (lawd_cd, deal_ymd);

CREATE INDEX ix_rtms_backfill_chunk_last_run
    ON rtms_backfill_chunk (last_run_id)
    WHERE last_run_id IS NOT NULL;
