CREATE TABLE news_source_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(64) NOT NULL,
    source_class VARCHAR(64) NOT NULL CHECK (
        source_class IN ('LICENSED_API', 'SEARCH_API', 'RSS', 'PUBLIC_AGENCY', 'PUBLISHER_PAGE')
    ),
    usage_status VARCHAR(64) NOT NULL CHECK (
        usage_status IN ('ALLOWED', 'REVIEW_REQUIRED', 'BLOCKED')
    ),
    full_text_allowed BOOLEAN NOT NULL DEFAULT false,
    replacement_summary_allowed BOOLEAN NOT NULL DEFAULT false CHECK (replacement_summary_allowed = false),
    terms_url TEXT,
    robots_url TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_news_source_policy_source UNIQUE (source)
);

CREATE TABLE news_article_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(64) NOT NULL REFERENCES news_source_policy (source),
    source_key VARCHAR(512) NOT NULL,
    publisher VARCHAR(255) NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    provider_url TEXT,
    snippet TEXT,
    published_at TIMESTAMPTZ,
    provider_pub_at TIMESTAMPTZ,
    first_seen_at TIMESTAMPTZ NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    news_date_kst DATE NOT NULL,
    raw_provider_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    payload_hash VARCHAR(128),
    ingest_status VARCHAR(64) NOT NULL CHECK (
        ingest_status IN (
            'OBSERVED',
            'FEATURED',
            'DUPLICATE',
            'SKIPPED_IRRELEVANT',
            'FETCH_FAILED',
            'TERMS_BLOCKED',
            'PARSE_FAILED'
        )
    ),
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_news_article_observation_source_key UNIQUE (source, source_key),
    CONSTRAINT ck_news_article_observation_payload_metadata_only CHECK (
        NOT jsonb_path_exists(raw_provider_payload, '$.**.content')
        AND NOT jsonb_path_exists(raw_provider_payload, '$.**.body')
        AND NOT jsonb_path_exists(raw_provider_payload, '$.**.full_text')
        AND NOT jsonb_path_exists(raw_provider_payload, '$.**.html')
        AND NOT jsonb_path_exists(raw_provider_payload, '$.**.article_html')
    )
);

CREATE INDEX ix_news_article_observation_first_seen
    ON news_article_observation (first_seen_at, id);

CREATE INDEX ix_news_article_observation_news_date
    ON news_article_observation (news_date_kst, id);

CREATE INDEX ix_news_article_observation_ingest_status
    ON news_article_observation (ingest_status, id);

CREATE TABLE news_signal_feature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_observation_id BIGINT NOT NULL REFERENCES news_article_observation (id) ON DELETE CASCADE,
    source VARCHAR(64) NOT NULL,
    source_key VARCHAR(512) NOT NULL,
    feature_date_kst DATE NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL,
    region_tags JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(region_tags) = 'array'),
    complex_candidates JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(complex_candidates) = 'array'),
    topic_tags JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(topic_tags) = 'array'),
    impact_target VARCHAR(32) NOT NULL CHECK (
        impact_target IN ('sale_price', 'jeonse_price', 'volume', 'supply', 'liquidity', 'risk')
    ),
    impact_direction VARCHAR(16) NOT NULL CHECK (
        impact_direction IN ('up', 'down', 'mixed', 'unknown')
    ),
    sentiment VARCHAR(16) NOT NULL CHECK (
        sentiment IN ('positive', 'neutral', 'negative', 'mixed')
    ),
    confidence NUMERIC(5, 4) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    extraction_version VARCHAR(64) NOT NULL,
    evidence_level VARCHAR(64) NOT NULL CHECK (
        evidence_level IN ('title', 'snippet', 'licensed_full_text', 'public_press_release')
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_news_signal_feature_observation_source_key
        FOREIGN KEY (source, source_key)
        REFERENCES news_article_observation (source, source_key)
        ON DELETE CASCADE,
    CONSTRAINT uq_news_signal_feature_observation_version
        UNIQUE (article_observation_id, extraction_version)
);

CREATE INDEX ix_news_signal_feature_cutoff
    ON news_signal_feature (first_seen_at, feature_date_kst, id);

CREATE INDEX ix_news_signal_feature_feature_date
    ON news_signal_feature (feature_date_kst, id);

CREATE INDEX ix_news_signal_feature_region_tags
    ON news_signal_feature USING GIN (region_tags);

CREATE INDEX ix_news_signal_feature_topic_tags
    ON news_signal_feature USING GIN (topic_tags);
