CREATE TABLE news_relevance_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_observation_id BIGINT NOT NULL REFERENCES news_article_observation (id) ON DELETE CASCADE,
    source VARCHAR(64) NOT NULL,
    source_key VARCHAR(512) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    decision VARCHAR(32) NOT NULL CHECK (
        decision IN ('KEEP', 'REVIEW', 'SKIP_IRRELEVANT')
    ),
    score NUMERIC(5, 4) NOT NULL CHECK (score >= 0 AND score <= 1),
    threshold NUMERIC(5, 4) NOT NULL CHECK (threshold >= 0 AND threshold <= 1),
    reason_codes JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(reason_codes) = 'array'),
    matched_terms JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(matched_terms) = 'object'),
    evaluated_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_news_relevance_decision_observation_source_key
        FOREIGN KEY (source, source_key)
        REFERENCES news_article_observation (source, source_key)
        ON DELETE CASCADE,
    CONSTRAINT uq_news_relevance_decision_observation_policy
        UNIQUE (article_observation_id, policy_version)
);

CREATE INDEX ix_news_relevance_decision_decision
    ON news_relevance_decision (decision, evaluated_at, id);

CREATE INDEX ix_news_relevance_decision_source_key
    ON news_relevance_decision (source, source_key);
