CREATE TABLE news_collection_keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_text TEXT NOT NULL,
    keyword_type VARCHAR(32) NOT NULL CHECK (
        keyword_type IN ('TOPIC', 'REGION', 'COMPLEX', 'ALIAS')
    ),
    source_table VARCHAR(64),
    source_id VARCHAR(128),
    priority INTEGER NOT NULL DEFAULT 100,
    cadence VARCHAR(32) NOT NULL DEFAULT 'DAILY' CHECK (
        cadence IN ('DAILY', 'WEEKLY', 'MANUAL')
    ),
    enabled BOOLEAN NOT NULL DEFAULT true,
    next_due_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_collected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_news_collection_keyword_query_text CHECK (btrim(query_text) <> ''),
    CONSTRAINT ck_news_collection_keyword_source_pair CHECK (
        (source_table IS NULL AND source_id IS NULL)
        OR (source_table IS NOT NULL AND source_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_news_collection_keyword_identity
    ON news_collection_keyword (keyword_type, query_text, source_table, source_id) NULLS NOT DISTINCT;

CREATE INDEX ix_news_collection_keyword_due
    ON news_collection_keyword (enabled, next_due_at, priority DESC, id);

CREATE TABLE news_collection_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_type VARCHAR(32) NOT NULL DEFAULT 'SCHEDULED' CHECK (
        trigger_type IN ('SCHEDULED', 'MANUAL')
    ),
    status VARCHAR(32) NOT NULL CHECK (
        status IN ('STARTED', 'SKIPPED', 'COMPLETED', 'PARTIAL', 'FAILED')
    ),
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    keyword_count INTEGER NOT NULL DEFAULT 0 CHECK (keyword_count >= 0),
    read_count BIGINT NOT NULL DEFAULT 0 CHECK (read_count >= 0),
    observed_count BIGINT NOT NULL DEFAULT 0 CHECK (observed_count >= 0),
    duplicate_skipped_count BIGINT NOT NULL DEFAULT 0 CHECK (duplicate_skipped_count >= 0),
    relevance_evaluated_count BIGINT NOT NULL DEFAULT 0 CHECK (relevance_evaluated_count >= 0),
    relevance_kept_count BIGINT NOT NULL DEFAULT 0 CHECK (relevance_kept_count >= 0),
    relevance_skipped_irrelevant_count BIGINT NOT NULL DEFAULT 0 CHECK (relevance_skipped_irrelevant_count >= 0),
    extraction_evaluated_count BIGINT NOT NULL DEFAULT 0 CHECK (extraction_evaluated_count >= 0),
    extracted_count BIGINT NOT NULL DEFAULT 0 CHECK (extracted_count >= 0),
    duplicate_feature_skipped_count BIGINT NOT NULL DEFAULT 0 CHECK (duplicate_feature_skipped_count >= 0),
    export_date DATE,
    export_path TEXT,
    export_feature_count INTEGER NOT NULL DEFAULT 0 CHECK (export_feature_count >= 0),
    export_article_count INTEGER NOT NULL DEFAULT 0 CHECK (export_article_count >= 0),
    export_truncated BOOLEAN NOT NULL DEFAULT false,
    notification_status VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUESTED' CHECK (
        notification_status IN ('NOT_REQUESTED', 'SENT', 'FAILED')
    ),
    notification_failure_reason TEXT,
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_news_collection_run_started
    ON news_collection_run (started_at DESC, id DESC);

CREATE INDEX ix_news_collection_run_status
    ON news_collection_run (status, started_at DESC, id DESC);

CREATE TABLE news_collection_run_keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES news_collection_run (id) ON DELETE CASCADE,
    keyword_id BIGINT REFERENCES news_collection_keyword (id) ON DELETE SET NULL,
    query_text TEXT NOT NULL,
    keyword_type VARCHAR(32) NOT NULL CHECK (
        keyword_type IN ('TOPIC', 'REGION', 'COMPLEX', 'ALIAS')
    ),
    source_table VARCHAR(64),
    source_id VARCHAR(128),
    priority INTEGER NOT NULL,
    cadence VARCHAR(32) NOT NULL CHECK (
        cadence IN ('DAILY', 'WEEKLY', 'MANUAL')
    ),
    status VARCHAR(32) NOT NULL CHECK (
        status IN ('STARTED', 'SKIPPED', 'COMPLETED', 'PARTIAL', 'FAILED')
    ),
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    read_count BIGINT NOT NULL DEFAULT 0 CHECK (read_count >= 0),
    observed_count BIGINT NOT NULL DEFAULT 0 CHECK (observed_count >= 0),
    duplicate_skipped_count BIGINT NOT NULL DEFAULT 0 CHECK (duplicate_skipped_count >= 0),
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_news_collection_run_keyword_query_text CHECK (btrim(query_text) <> '')
);

CREATE INDEX ix_news_collection_run_keyword_run
    ON news_collection_run_keyword (run_id, id);

CREATE INDEX ix_news_collection_run_keyword_status
    ON news_collection_run_keyword (status, started_at DESC, id DESC);

CREATE TABLE news_collection_run_article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_keyword_id BIGINT NOT NULL REFERENCES news_collection_run_keyword (id) ON DELETE CASCADE,
    source VARCHAR(64) NOT NULL,
    source_key VARCHAR(512) NOT NULL,
    provider_rank INTEGER NOT NULL CHECK (provider_rank >= 1),
    disposition VARCHAR(32) NOT NULL CHECK (
        disposition IN ('OBSERVED', 'DUPLICATE')
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_news_collection_run_article_observation_source_key
        FOREIGN KEY (source, source_key)
        REFERENCES news_article_observation (source, source_key)
        ON DELETE CASCADE,
    CONSTRAINT uq_news_collection_run_article_keyword_source_key
        UNIQUE (run_keyword_id, source, source_key)
);

CREATE INDEX ix_news_collection_run_article_source_key
    ON news_collection_run_article (source, source_key);
