CREATE SCHEMA IF NOT EXISTS reference;

CREATE TABLE reference.coordinate_snapshot_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_version VARCHAR(64) NOT NULL,
    source_dataset VARCHAR(64) NOT NULL DEFAULT 'VWORLD_CONTINUOUS_CADASTRAL',
    source_dir TEXT,
    source_srid INTEGER NOT NULL DEFAULT 5186,
    target_srid INTEGER NOT NULL DEFAULT 4326,
    status VARCHAR(32) NOT NULL CHECK (
        status IN ('STARTED', 'PASSED', 'FAILED', 'ROLLED_BACK')
    ),
    file_count INTEGER NOT NULL DEFAULT 0 CHECK (file_count >= 0),
    region_count INTEGER NOT NULL DEFAULT 0 CHECK (region_count >= 0),
    raw_feature_count BIGINT NOT NULL DEFAULT 0 CHECK (raw_feature_count >= 0),
    pnu_count BIGINT NOT NULL DEFAULT 0 CHECK (pnu_count >= 0),
    invalid_count BIGINT NOT NULL DEFAULT 0 CHECK (invalid_count >= 0),
    duplicate_pnu_count BIGINT NOT NULL DEFAULT 0 CHECK (duplicate_pnu_count >= 0),
    synced_parcel_count BIGINT NOT NULL DEFAULT 0 CHECK (synced_parcel_count >= 0),
    report_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    failure_reason TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ
);

CREATE INDEX ix_coordinate_snapshot_run_status_started
    ON reference.coordinate_snapshot_run (status, started_at DESC);

CREATE TABLE reference.parcel_coordinate_snapshot (
    pnu VARCHAR(19) PRIMARY KEY CHECK (pnu ~ '^[0-9]{19}$'),
    region_code VARCHAR(8) NOT NULL,
    latitude NUMERIC(10, 7) NOT NULL CHECK (latitude BETWEEN 33 AND 39),
    longitude NUMERIC(10, 7) NOT NULL CHECK (longitude BETWEEN 124 AND 132),
    point geometry(Point, 4326) NOT NULL,
    geom geometry(MultiPolygon, 4326) NOT NULL,
    snapshot_version VARCHAR(64) NOT NULL,
    source_file TEXT NOT NULL,
    run_id BIGINT REFERENCES reference.coordinate_snapshot_run (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_parcel_coordinate_snapshot_point_srid CHECK (ST_SRID(point) = 4326),
    CONSTRAINT ck_parcel_coordinate_snapshot_geom_srid CHECK (ST_SRID(geom) = 4326),
    CONSTRAINT ck_parcel_coordinate_snapshot_geom_valid CHECK (ST_IsValid(geom))
);

CREATE INDEX ix_parcel_coordinate_snapshot_region_code
    ON reference.parcel_coordinate_snapshot (region_code);

CREATE INDEX ix_parcel_coordinate_snapshot_geom
    ON reference.parcel_coordinate_snapshot USING GIST (geom);

CREATE INDEX ix_parcel_coordinate_snapshot_point
    ON reference.parcel_coordinate_snapshot USING GIST (point);
