CREATE TABLE odcloud_pnu_prefix_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_prefix CHAR(8) NOT NULL CHECK (canonical_prefix ~ '^[0-9]{8}$'),
    source_prefix CHAR(8) NOT NULL CHECK (source_prefix ~ '^[0-9]{8}$'),
    status VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'DISABLED')),
    reason TEXT,
    requested_by VARCHAR(128),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_by VARCHAR(128),
    approved_at TIMESTAMPTZ,
    disabled_by VARCHAR(128),
    disabled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_odcloud_pnu_prefix_alias UNIQUE (canonical_prefix, source_prefix),
    CONSTRAINT ck_odcloud_pnu_prefix_alias_distinct CHECK (canonical_prefix <> source_prefix)
);

CREATE UNIQUE INDEX uq_odcloud_pnu_prefix_alias_approved_canonical
    ON odcloud_pnu_prefix_alias (canonical_prefix)
    WHERE status = 'APPROVED';

ALTER TABLE complex_metadata_enrichment_attempt
    ADD COLUMN lookup_path VARCHAR(32),
    ADD COLUMN requested_pnu VARCHAR(19),
    ADD COLUMN resolved_source_pnu VARCHAR(19),
    ADD COLUMN alias_id BIGINT REFERENCES odcloud_pnu_prefix_alias(id),
    ADD COLUMN candidate_count INTEGER CHECK (candidate_count IS NULL OR candidate_count >= 0);

ALTER TABLE complex_metadata_enrichment_attempt
    ADD CONSTRAINT ck_cmea_lookup_path CHECK (
        lookup_path IS NULL
        OR lookup_path IN ('CANONICAL_PNU', 'APPROVED_PREFIX_ALIAS', 'COMPLEX_PK_DIAGNOSTIC', 'BUILDING_PNU', 'NONE')
    ),
    ADD CONSTRAINT ck_cmea_requested_pnu CHECK (requested_pnu IS NULL OR requested_pnu ~ '^[0-9]{19}$'),
    ADD CONSTRAINT ck_cmea_resolved_source_pnu CHECK (
        resolved_source_pnu IS NULL OR resolved_source_pnu ~ '^[0-9]{19}$'
    );

INSERT INTO odcloud_pnu_prefix_alias (
    canonical_prefix, source_prefix, status, reason, requested_by, approved_by, approved_at
)
VALUES
    ('41461262', '41461360', 'APPROVED', 'ODC legacy PNU: 양지면에서 양지읍 승격 미반영', 'flyway:V32', 'flyway:V32', now()),
    ('43770256', '43770340', 'APPROVED', 'ODC legacy PNU: 대소면에서 대소읍 승격 미반영', 'flyway:V32', 'flyway:V32', now());
