ALTER TABLE complex
    ADD COLUMN metadata_hold_at TIMESTAMPTZ,
    ADD COLUMN metadata_hold_reason TEXT,
    ADD COLUMN metadata_hold_by VARCHAR(128);

CREATE TABLE complex_metadata_admin_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complex_id BIGINT REFERENCES complex(id) ON DELETE CASCADE,
    alias_id BIGINT REFERENCES odcloud_pnu_prefix_alias(id),
    decision_type VARCHAR(24) NOT NULL CHECK (
        decision_type IN ('RETRY_REQUESTED', 'HOLD', 'ALIAS_PROPOSED', 'ALIAS_APPROVED', 'ALIAS_DISABLED')
    ),
    actor VARCHAR(128) NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_complex_metadata_admin_decision_target CHECK (
        (decision_type IN ('RETRY_REQUESTED', 'HOLD') AND complex_id IS NOT NULL AND alias_id IS NULL)
        OR
        (decision_type IN ('ALIAS_PROPOSED', 'ALIAS_APPROVED', 'ALIAS_DISABLED') AND alias_id IS NOT NULL AND complex_id IS NULL)
    )
);

CREATE INDEX ix_complex_metadata_admin_decision_complex
    ON complex_metadata_admin_decision (complex_id, created_at DESC);

CREATE INDEX ix_complex_metadata_admin_decision_alias
    ON complex_metadata_admin_decision (alias_id, created_at DESC);

UPDATE complex
SET metadata_next_attempt_at = now(),
    updated_at = now()
WHERE metadata_status IN ('UNAVAILABLE', 'FAILED', 'PARTIAL')
  AND metadata_hold_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM parcel p
      JOIN odcloud_pnu_prefix_alias alias
        ON alias.canonical_prefix = substring(p.pnu, 1, 8)
       AND alias.status = 'APPROVED'
      WHERE p.id = complex.parcel_id
  );
