CREATE TABLE complex_name_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complex_id BIGINT NOT NULL REFERENCES complex (id) ON DELETE CASCADE,
    alias_type VARCHAR(32) NOT NULL CHECK (
        alias_type IN (
            'TRADE_NAME',
            'BUILDING_REGISTER_NAME',
            'RTMS_APT_NAME',
            'ADMIN_ALIAS',
            'SOURCE_ALIAS'
        )
    ),
    alias_name VARCHAR(255) NOT NULL,
    normalized_name VARCHAR(255) NOT NULL,
    source VARCHAR(32),
    source_key VARCHAR(255),
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_complex_name_alias UNIQUE (complex_id, alias_type, normalized_name)
);

CREATE INDEX ix_complex_name_alias_lookup ON complex_name_alias (normalized_name, complex_id);
CREATE INDEX ix_complex_name_alias_source ON complex_name_alias (source, source_key);
