CREATE TABLE trade_match_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_ingest_id BIGINT NOT NULL REFERENCES raw_trade_ingest (id) ON DELETE CASCADE,
    source VARCHAR(32) NOT NULL,
    raw_jibun VARCHAR(255),
    normalized_jibun VARCHAR(255),
    sgg_cd VARCHAR(16),
    umd_cd VARCHAR(16),
    land_code VARCHAR(1),
    bonbun VARCHAR(4),
    bubun VARCHAR(4),
    derived_pnu VARCHAR(19),
    pnu_unavailable_reason TEXT,
    apt_seq VARCHAR(64),
    apt_name VARCHAR(255),
    match_status VARCHAR(32) NOT NULL CHECK (
        match_status IN (
            'MATCHED',
            'MATCHED_NAME_VARIANT',
            'PNU_CONFLICT',
            'NAME_CONFLICT',
            'AMBIGUOUS',
            'PNU_UNAVAILABLE',
            'UNMATCHED'
        )
    ),
    match_path VARCHAR(64),
    matched_complex_id BIGINT REFERENCES complex (id),
    matched_complex_pk VARCHAR(64),
    candidate_count INTEGER NOT NULL DEFAULT 0 CHECK (candidate_count >= 0),
    candidate_complex_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_trade_match_evidence_raw UNIQUE (raw_ingest_id)
);

CREATE INDEX ix_trade_match_evidence_status
    ON trade_match_evidence (match_status, id);

CREATE INDEX ix_trade_match_evidence_derived_pnu
    ON trade_match_evidence (derived_pnu)
    WHERE derived_pnu IS NOT NULL;
