CREATE TABLE rtms_ingest_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lawd_cd VARCHAR(16) NOT NULL,
    deal_ymd VARCHAR(8) NOT NULL,
    status VARCHAR(32) NOT NULL CHECK (status IN ('COMPLETED')),
    page_count INTEGER NOT NULL CHECK (page_count >= 0),
    read_count BIGINT NOT NULL CHECK (read_count >= 0),
    raw_saved_count BIGINT NOT NULL CHECK (raw_saved_count >= 0),
    normalized_inserted_count BIGINT NOT NULL CHECK (normalized_inserted_count >= 0),
    duplicate_skipped_count BIGINT NOT NULL CHECK (duplicate_skipped_count >= 0),
    match_failed_count BIGINT NOT NULL CHECK (match_failed_count >= 0),
    parse_failed_count BIGINT NOT NULL CHECK (parse_failed_count >= 0),
    failure_reason TEXT,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_rtms_ingest_run_month ON rtms_ingest_run (lawd_cd, deal_ymd, id DESC);
CREATE INDEX ix_rtms_ingest_run_status ON rtms_ingest_run (status, id DESC);
