services:
  api:
    environment:
      HOME_INGEST_RTMS_DAILY_ENABLED: "true"
      HOME_INGEST_RTMS_DAILY_LAWD_CDS: "11680,11710,11650"
      HOME_INGEST_RTMS_DAILY_CRON: "0 * * * * *"
      HOME_INGEST_RTMS_DAILY_HERMES_ENABLED: "true"
