spring:
  application:
    name: home-search-property-data-migration
  main:
    web-application-type: none
  datasource:
    url: "${DB_JDBC_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
