pluginManagement { repositories { gradlePluginPortal(); mavenCentral() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { mavenCentral() } }
rootProject.name = 'home-search-admin-service'
include 'core', 'api', 'migration', 'ops'
includeBuild('../../../libs/security-jwt-core') {
    dependencySubstitution {
        substitute module('com.home:security-jwt-core') using project(':')
    }
}
